-- ========================================================================
-- ExploreTN — Tamil Nadu Structured Places Seed Dataset
-- Rich Tamil & English canonical destinations with exact spatial coordinates
-- ========================================================================

INSERT INTO public.places (
  slug, name, tamil_name, tagline, tamil_tagline, district, taluk, category, subcategories,
  description, tamil_description, latitude, longitude, address, pincode, opening_hours,
  best_time_to_visit, entry_fee_inr, entry_fee_info, rating, review_count, image_url, gallery_urls,
  tags, is_featured, is_verified, visibility, status
) VALUES
-- 1. MADURAI - MEENAKSHI AMMAN TEMPLE
(
  'meenakshi-amman-temple-madurai',
  'Meenakshi Amman Temple',
  'மீனாட்சி அம்மன் கோவில்',
  'Historic Dravidian masterpiece with 14 towering gopurams',
  '14 பிரம்மாண்ட கோபுரங்கள் கொண்ட திராவிடக் கட்டிடக்கலை அற்புதம்',
  'Madurai',
  'Madurai North',
  'Temple',
  ARRAY['Dravidian Architecture', 'Spiritual', 'Heritage', 'UNESCO Nominee'],
  'The crown jewel of Madurai, dedicated to Goddess Meenakshi and Lord Sundareswarar. Features 14 towering gopurams decorated with thousands of painted stone figures, the 1,000-pillared hall (Aayiram Kaal Mandapam), and the sacred Golden Lotus Tank (Pottramarai Kulam).',
  'மதுரையின் திலகமாக விளங்கும் உலகப் புகழ்பெற்ற மீனாட்சி சுந்தரேஸ்வரர் திருக்கோவில். 14 வண்ணமயமான கோபுரங்கள், ஆயிரம் கால் மண்டபம் மற்றும் பொற்றாமரைக் குளம் கொண்ட வரலாற்றுச் சிறப்புமிக்க ஆன்மீக மையம்.',
  9.9195000,
  78.1193000,
  'Madurai Main, Town Hall Road, Madurai',
  '625001',
  '5:00 AM - 12:30 PM, 4:00 PM - 9:30 PM',
  'October to March (Chithirai Thiruvizha in April)',
  0.00,
  'Free entry for temple main complex',
  4.95,
  12450,
  '/assets/places/meenakshi-amman.jpg',
  ARRAY['/assets/places/meenakshi-gopuram.jpg', '/assets/places/meenakshi-tank.jpg'],
  ARRAY['temple', 'madurai', 'dravidian', 'gopuram', 'heritage'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 2. MADURAI - PUTHU MANDAPAM
(
  'puthu-mandapam-thrift-market-madurai',
  'Puthu Mandapam Ancient Thrift Bazaar',
  'புது மண்டபம் ஆடை தைப்பகம் & பாரம்பரிய கடைத்தெரு',
  '400-year-old pillared tailoring hall and artisan silk bazaar',
  '400 ஆண்டுகள் பழமையான கல்தூண் மண்டப தையல் கலைக்கடைகள்',
  'Madurai',
  'Madurai South',
  'Thrift Street',
  ARRAY['Tailoring', 'Handloom', 'Silk', 'Brassware', 'Heritage Market'],
  'Constructed by King Thirumalai Nayak in 1635 directly opposite the East Gopuram. Home to over 150 vintage sewing machines, heritage tailors, silk merchants, and brassware artisans working inside historic stone carved pillars.',
  'திருமலை நாயக்கரால் 1635-இல் கட்டப்பட்ட வரலாற்றுச் சிறப்புமிக்க கல்தூண் மண்டபம். கிழக்கு கோபுரத்தின் எதிரே தையல் கலைஞர்கள், பட்டு வியபாரிகள் மற்றும் பித்தளைக் கைவினைஞர்களின் வரலாற்றுச் சந்தை.',
  9.9198000,
  78.1210000,
  'Opposite East Tower, Meenakshi Temple Street, Madurai',
  '625001',
  '9:30 AM - 9:00 PM',
  'All Year Round',
  0.00,
  'Free Entry',
  4.85,
  3890,
  '/assets/places/puthu-mandapam.jpg',
  ARRAY['/assets/places/puthu-mandapam-tailors.jpg'],
  ARRAY['thrift', 'madurai', 'bazaar', 'heritage', 'silk'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 3. MADURAI - FAMOUS JIGARTHANDA
(
  'famous-jigarthanda-town-hall-road-madurai',
  'Famous Jigarthanda (Town Hall Road)',
  'ஃபேமஸ் ஜிகர்தண்டா (டவுன் ஹால் ரோடு)',
  'Madura''s signature cooling drink made with almond gum and basundi',
  'மதுரையின் பெருமைமிகு பாதாம் பிசின் & பாசந்தி குளிர் பானம்',
  'Madurai',
  'Madurai Central',
  'Food Spot',
  ARRAY['Street Food', 'Beverage', 'Dessert', 'Iconic Taste'],
  'The authentic home of Jigarthanda (meaning "Heart Cooler"). Prepared using organic badam pisin (almond gum), nannari sarsaparilla syrup, reduced caramelized milk, and topped with rich homemade basundi ice cream.',
  'மதுரையின் இதயம் குளிர்ந்த பானம்! இயற்கை பாதாம் பிசின், நன்னாரி சர்பத், சுண்டக்காய்ச்சிய பால் மற்றும் பிரத்யேக பாசந்தி ஐஸ்கிரீம் கலந்த சுவையான குளிர்பானம்.',
  9.9160000,
  78.1140000,
  '14, Town Hall Road, Madurai',
  '625001',
  '10:00 AM - 11:00 PM',
  'All Year Round (Best in Summer)',
  80.00,
  '₹80 (Special) / ₹120 (Super Special)',
  4.90,
  8210,
  '/assets/places/jigarthanda.jpg',
  ARRAY['/assets/places/jigarthanda-glass.jpg'],
  ARRAY['food', 'madurai', 'jigarthanda', 'street-food', 'dessert'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 4. THANJAVUR - BRIHADEESWARAR TEMPLE (BIG TEMPLE)
(
  'brihadeeswarar-temple-thanjavur',
  'Brihadeeswarar Temple (Thanjavur Big Temple)',
  'தஞ்சாவூர் பிரகதீஸ்வரர் கோவில் (பெரிய கோவில்)',
  '1,000-year-old Chola architectural wonder & UNESCO World Heritage site',
  'சோழப் பேரரசின் 1000 ஆண்டுகள் பழமையான யுனெஸ்கோ உலகப் பாரம்பரியச் சின்னம்',
  'Thanjavur',
  'Thanjavur North',
  'Heritage',
  ARRAY['UNESCO World Heritage', 'Chola Architecture', 'Granite Monolith', 'Spiritual'],
  'Built by Emperor Raja Raja Chola I in 1010 AD. Known for its 216-ft vimana hollow tower made entirely of interlocking granite, single-stone 80-ton Kumbam cap, and giant Nandi monolith.',
  'முதலாம் இராஜராஜ சோழனால் கி.பி 1010-இல் கட்டப்பட்ட கட்டடக் கலை அற்புதம். 216 அடி உயர கருங்கல் விமானம் மற்றும் 80 டன் எடையுள்ள ஒரே கல் சிகரம் கொண்ட உலகப் புகழ்பெற்ற கோவில்.',
  10.7828000,
  79.1318000,
  'Membalam Road, Balaganapathy Nagar, Thanjavur',
  '613007',
   meenakshi -> '6:00 AM - 12:30 PM, 4:00 PM - 8:30 PM',
  'October to March',
  0.00,
  'Free Entry (Archaeological Survey of India maintained)',
  4.97,
  15200,
  '/assets/places/thanjavur-big-temple.jpg',
  ARRAY['/assets/places/thanjavur-nandi.jpg', '/assets/places/thanjavur-tower.jpg'],
  ARRAY['thanjavur', 'chola', 'unesco', 'big-temple', 'heritage'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 5. NILGIRIS - OOTY BOTANICAL GARDENS & SHOLA PASS
(
  'government-botanical-garden-ooty',
  'Government Botanical Garden Ooty',
  'அரசு தாவரவியல் பூங்கா உதகமண்டலம்',
  '55-acre high-altitude flora paradise established in 1848',
  'நீலகிரி மலையில் 55 ஏக்கரில் அமைந்துள்ள 175 ஆண்டுகள் பழமையான தாவரவியல் பூங்கா',
  'Nilgiris',
  'Udhagamandalam',
  'Hill Station',
  ARRAY['Nature', 'Flora', 'High Altitude', 'Fossil Tree'],
  'Laid out in 1848 on the slopes of Doddabetta peak. Features over 1,000 species of exotic plants, a 20-million-year-old fossilized tree trunk, Italian garden terracing, and vibrant annual flower shows.',
  '1848-இல் தொட்டபெட்டா சிகரச் சரிவில் அமைக்கப்பட்ட எழில்மிகு தாவரவியல் பூங்கா. 1000-க்கும் மேற்பட்ட அபூர்வ தாவரங்கள் மற்றும் 2 கோடி ஆண்டுகள் பழமையான மரப் படிமம் கொண்ட இயற்கை சொர்க்கம்.',
  11.4167000,
  76.7117000,
  'Vanguard Road, Udhagamandalam, Nilgiris',
  '643001',
  '7:00 AM - 6:30 PM',
  'September to May',
  40.00,
  '₹40 (Adults) / ₹20 (Children) / ₹50 (Still Camera)',
  4.82,
  9400,
  '/assets/places/ooty-botanical-garden.jpg',
  ARRAY['/assets/places/ooty-flowers.jpg'],
  ARRAY['ooty', 'nilgiris', 'hill-station', 'botanical-garden', 'nature'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 6. MAHABALIPURAM - SHORE TEMPLE & SHORELINE MONUMENTS
(
  'shore-temple-mahabalipuram',
  'Shore Temple & Monolithic Rathas',
  'மாமல்லபுரம் கடற்கரைக் கோவில் & பஞ்ச ரதங்கள்',
  '7th-century Pallava coastal rock-cut temples facing the Bay of Bengal',
  'பல்லவ மன்னர்களின் 7-ஆம் நூற்றாண்டு வங்காள விரிகுடா கடற்கரை குடைவரைக் கோவில்கள்',
  'Chengalpattu',
  'Tirukalukundram',
  'Heritage',
  ARRAY['UNESCO World Heritage', 'Pallava Dynasty', 'Rock-cut Architecture', 'Coastal'],
  'Built during the reign of King Narasimhavarman II (700–728 AD). Perched on the edge of the Bay of Bengal, featuring 5 monolithic Pancha Rathas carved from single boulders and Arjuna''s Penance bas-relief.',
  'கி.பி 8-ஆம் நூற்றாண்டில் நரசிம்மவர்மன் காலத்தில் கட்டப்பட்ட யுனெஸ்கோ உலகப் பாரம்பரிய கடற்கரைக் கோவில். பஞ்ச ரதங்கள் மற்றும் அர்ஜுனன் தபசு பாறைச் சிற்பங்கள் கொண்ட பல்லவ கலைக் கூடம்.',
  12.6163000,
  80.1983000,
  'Shore Temple Road, Mahabalipuram, Chengalpattu',
  '603104',
  '6:00 AM - 6:00 PM',
  'October to March',
  40.00,
  '₹40 for Indian Citizens / ₹600 for Foreign Tourists',
  4.91,
  11300,
  '/assets/places/shore-temple.jpg',
  ARRAY['/assets/places/pancha-rathas.jpg'],
  ARRAY['mahabalipuram', 'pallava', 'unesco', 'beach', 'heritage'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 7. KANYAKUMARI - VIVEKANANDA ROCK MEMORIAL & THIRUVALLUVAR STATUE
(
  'vivekananda-rock-memorial-kanyakumari',
  'Vivekananda Rock Memorial & Thiruvalluvar Statue',
  'விவேகானந்தர் பாறை நினைவாலயம் & திருவள்ளுவர் சிலை',
  'Confluence of three oceans where Swami Vivekananda meditated',
  'முக்கடல் சங்கமத்தில் அமைந்துள்ள 133 அடி திருவள்ளுவர் சிலை & விவேகானந்தர் பாறை',
  'Kanyakumari',
  'Agastheeswaram',
  'Heritage',
  ARRAY['Triveni Sangam', 'Monuments', 'Islet', 'Ocean View'],
  'Standing on a rock island 500 meters off the coast of Triveni Sangam (confluence of Indian Ocean, Arabian Sea, and Bay of Bengal). Features the 133-ft stone Thiruvalluvar statue representing the 133 chapters of Thirukkural.',
  'முக்கடலும் சந்திக்கும் முனைக்கு 500 மீட்டர் தொலைவில் அமைந்துள்ள விவேகானந்தர் பாறை மற்றும் 133 அதிகாரங்களைக் குறிக்கும் 133 அடி உயரப் பிரம்மாண்ட திருவள்ளுவர் சிலை.',
  8.0781000,
  77.5554000,
  'Sunset Point Road, Kanyakumari',
  '629702',
  '8:00 AM - 4:00 PM',
  'October to March',
  50.00,
  '₹50 Ferry ticket + ₹20 Entry ticket',
  4.94,
  14100,
  '/assets/places/vivekananda-rock.jpg',
  ARRAY['/assets/places/thiruvalluvar-statue.jpg'],
  ARRAY['kanyakumari', 'thiruvalluvar', 'sangam', 'ocean', 'monument'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 8. CHENNAI - KNK ROAD
(
  'knk-road',
  'Khader Nawaz Khan Road (KNK Road)',
  'காதர் நவாஸ் கான் சாலை (கே.என்.கே ரோடு)',
  'Chennai premier luxury high-street fashion & lifestyle promenade',
  'சென்னையின் முன்னணி ஆடம்பர ஃபேஷன் மற்றும் உணவு விடுதிகள் அமைந்த நவீன வீதி',
  'Chennai',
  'Egmore-Nungambakkam',
  'Shopping',
  ARRAY['Luxury Shopping', 'High Street', 'Fine Dining', 'Boutiques'],
  'Khader Nawaz Khan Road (KNK Road) in Nungambakkam is Chennai signature upscale fashion and lifestyle Boulevard. Spanning pedestrian-friendly tree-lined sidewalks, it hosts luxury international brands, designer haute couture, artisan bakeries, and gourmet international restaurants.',
  'நுங்கம்பாக்கத்தில் அமைந்துள்ள கே.என்.கே சாலை சென்னையின் மிகவும் புகழ்பெற்ற ஆடம்பர ஃபேஷன், ஆடை வடிவமைப்பு மையங்கள் மற்றும் சர்வதேச உணவகங்கள் நிறைந்த நவீன பகுதியாகும்.',
  13.0607000,
  80.2462000,
  'Khader Nawaz Khan Road, Nungambakkam, Chennai',
  '600034',
  '11:00 AM - 10:30 PM',
  'Year-round (Best for evening dining & shopping)',
  0.00,
  'Free public high-street access',
  4.80,
  5200,
  'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['knk_road', 'nungambakkam', 'shopping', 'fine_dining', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 9. CHENNAI - PHOENIX MARKETCITY VELACHERY
(
  'phoenix-marketcity-velachery',
  'Phoenix Marketcity Velachery',
  'ஃபீனிக்ஸ் மார்க்கெட்சிட்டி வேளச்சேரி',
  'South India premier retail mall, IMAX multiplex & entertainment city',
  'தென்னிந்தியாவின் முன்னணி பிரம்மாண்ட வணிக வளாகம் & ஐமேக்ஸ் திரையரங்கம்',
  'Chennai',
  'Velachery',
  'Shopping',
  ARRAY['Shopping Mall', 'IMAX Cinema', 'Gaming Zone', 'Food Court'],
  'Spanning over 1 million sq ft in Velachery, Phoenix Marketcity is one of South India premier shopping and entertainment complexes. Featuring over 300 international brands, the 11-screen Luxe IMAX multiplex, Palladium luxury wing, Fun City gaming, and a massive multi-cuisine food court.',
  'வேளச்சேரியில் அமைந்துள்ள 10 லட்சத்திற்கும் அதிகமான சதுர அடி பரப்பளவைக் கொண்ட பிரம்மாண்ட ஃபீனிக்ஸ் மார்க்கெட்சிட்டி, சர்வதேச ஆடம்பர பிராண்டுகள், ஐமேக்ஸ் திரையரங்கம் மற்றும் பொழுதுபோக்கு மையத்தைக் கொண்டுள்ளது.',
  12.9918000,
  80.2170000,
  '142, Velachery Main Road, Next to Checkpost, Velachery, Chennai',
  '600042',
  '10:00 AM - 10:00 PM',
  'Year-round',
  0.00,
  'Free entry to mall; ticketed cinema & games',
  4.75,
  18900,
  'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['phoenix_mall', 'velachery', 'imax', 'shopping', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 10. CHENNAI - BREAKTHRU ESCAPE ROOM
(
  'breakthru-college-road',
  'Breakthru - The Real Escape Room',
  'பிரேக்த்ரூ ரியல் எஸ்கேப் ரூம்',
  'Immersive 60-minute escape game adventure center on College Road',
  'நுங்கம்பாக்கத்தில் உள்ள 60 நிமிட புதிர் விளையாட்டு மையம்',
  'Chennai',
  'Egmore-Nungambakkam',
  'Adventure',
  ARRAY['Escape Room', 'Gaming', 'Interactive Puzzles', 'Team Challenge'],
  'Located on College Road in Nungambakkam, Breakthru is Chennai top-rated real-life escape room game center. Groups of 2 to 8 players solve mystery puzzles across themed chambers like The Crypt, Asylum Aftermath, Grand Theft Mobsters, and GBay Breakout within 60 minutes.',
  'நுங்கம்பாக்கம் காலேஜ் ரோட்டில் அமைந்துள்ள பிரேக்த்ரூ எஸ்கேப் ரூம், நண்பர்கள் மற்றும் குடும்பத்தினருடன் இணைந்து 60 நிமிடங்களில் புதிர்களை விடுவித்து வெளியேறும் விறுவிறுப்பான விளையாட்டு மையமாகும்.',
  13.0618000,
  80.2472000,
  '11/6, College Road, Thousand Lights West, Nungambakkam, Chennai',
  '600034',
  '11:00 AM - 9:30 PM',
  'Year-round',
  650.00,
  'Approx. ₹650 per person per 60-minute session',
  4.85,
  1420,
  'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['breakthru', 'escape_room', 'nungambakkam', 'gaming', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 11. KANCHIPURAM / CHENNAI - MADRAS INTERNATIONAL KARTING ARENA (MIKA)
(
  'madras-international-karting-arena',
  'Madras International Karting Arena (MIKA)',
  'மெட்ராஸ் இண்டர்நேஷனல் கார்ட்டிங் அரேனா (மீகா)',
  'World-class 1.2 km CIK-FIA standard go-kart circuit at Irungattukottai',
  'இருங்காட்டுக்கோட்டையில் அமைந்துள்ள உலகத்தரம் வாய்ந்த 1.2 கி.மீ கோ-கார்ட்டிங் ரேஸ் டிராக்',
  'Kanchipuram',
  'Sriperumbudur',
  'Sports',
  ARRAY['Go Karting', 'Motorsports', 'Race Circuit', 'Night Karting'],
  'Situated inside the historic Madras International Circuit (MIC) grounds at Irungattukottai near Sriperumbudur, MIKA is India premier 1.2 km CIK-FIA standard international go-karting track designed by Driven International with floodlit night racing and high-performance twin-engine Sodi karts.',
  'ஸ்ரீபெரும்புதூர் அருகே இருங்காட்டுக்கோட்டையில் மெட்ராஸ் இண்டர்நேஷனல் சர்க்யூட் வளாகத்தில் அமைந்துள்ள மீகா கார்ட்டிங் டிராக், 1.2 கி.மீ நீளமும் இரவு நேர ரேசிங் வெளிச்சமும் கொண்ட சர்வதேச தரத்திலான கோ-கார்ட்டிங் மையமாகும்.',
  13.0025000,
  79.9858000,
  'Madras International Circuit, NH4, Irungattukottai, Sriperumbudur',
  '602105',
  '2:00 PM - 10:00 PM (Closed Mondays)',
  'Year-round (Best for evening floodlit sessions)',
  750.00,
  'Ticketed karting sessions based on laps/duration',
  4.90,
  2100,
  'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['mika', 'go_karting', 'irungattukottai', 'sriperumbudur', 'motorsports'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 12. KANCHIPURAM / CHENNAI - SRIPERUMBUDUR
(
  'sriperumbudur',
  'Sriperumbudur Heritage & Industrial Hub',
  'ஸ்ரீபெரும்புதூர் ஆன்மீக & தொழில்துறை மையம்',
  'Birthplace of Sri Ramanujacharya & site of Rajiv Gandhi Memorial',
  'ஸ்ரீ ராமானுஜரின் அவதார தலம் & ராஜீவ் காந்தி நினைவாலயம்',
  'Kanchipuram',
  'Sriperumbudur',
  'Heritage',
  ARRAY['Ramanuja Temple', 'Rajiv Gandhi Memorial', 'Pilgrimage', 'History'],
  'Located 40 km west of Chennai along NH4, Sriperumbudur is a historic heritage town renowned as the 1017 CE birthplace of Sri Ramanujacharya (Sri Adikesava Perumal Temple) and the site of the solemn Rajiv Gandhi National Memorial.',
  'சென்னையிலிருந்து 40 கி.மீ தொலைவில் அமைந்துள்ள ஸ்ரீபெரும்புதூர், 1017 இல் அவதரித்த ஸ்ரீ ராமானுஜரின் பிறந்த தலமான ஆதிகேசவ பெருமாள் கோவில் மற்றும் ராஜீவ் காந்தி நினைவாலயம் அமைந்த வரலாற்று சிறப்புமிக்க நகரமாகும்.',
  12.9667000,
  79.9450000,
  'Sriperumbudur Town, NH4 Highway, Kanchipuram District',
  '602105',
  '6:00 AM - 12:00 PM, 4:00 PM - 8:00 PM',
  'October to March',
  0.00,
  'Free public entry for temples and memorial',
  4.70,
  3800,
  'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['sriperumbudur', 'ramanuja', 'rajiv_gandhi_memorial', 'temple', 'heritage'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 13. CHENNAI - VGP SNOW KINGDOM
(
  'vgp-snow-kingdom',
  'VGP Snow Kingdom (East Coast Road)',
  'வி.ஜி.பி ஸ்னோ கிங்டம் இ.சி.ஆர்',
  'India indoor sub-zero snow theme park at Injambakkam',
  'ஈஞ்சம்பாக்கத்தில் உள்ள மைனஸ் 8 டிகிரி பனிப் பொழிவு விளையாட்டு மையம்',
  'Chennai',
  'Sholinganallur',
  'Adventure',
  ARRAY['Snow Park', 'Sub Zero', 'Snow Slides', 'Igloos', 'Family Fun'],
  'Situated along ECR next to VGP Universal Kingdom in Injambakkam, VGP Snow Kingdom is a massive indoor winter wonderland maintained at -8°C. Visitors enjoy artificial snowfall, snow mountain slides, snowball fights, igloos, and ice sculptures.',
  'ஈஞ்சம்பாக்கம் இ.சி.ஆர் சாலையில் வி.ஜி.பி யுனிவர்சல் கிங்டம் அருகில் உள்ள ஸ்னோ கிங்டம், மைனஸ் 8 டிகிரி குளிரில் பனிச்சறுக்கு, பனிப்பொழிவு மற்றும் பனி வீடுகளை அனுபவிக்கும் பொழுதுபோக்கு மையமாகும்.',
  12.9131000,
  80.2511000,
  'East Coast Road, Injambakkam, Chennai',
  '600115',
  '10:00 AM - 8:00 PM',
  'Year-round',
  750.00,
  'Includes winter coat, boots & gloves',
  4.65,
  8900,
  'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['snow_kingdom', 'vgp', 'ecr', 'injambakkam', 'snow_park'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 14. CHENGALPATTU / ECR - MAHAB'S GLOW GARDEN
(
  'glow-garden-mahabalipuram',
  'Mahab Glow Garden (Mahabalipuram)',
  'மகாபலிபுரம் க்ளோ கார்டன்',
  'Magical night-time illuminated park with giant LED light sculptures',
  'மகாபலிபுரத்தில் உள்ள இரவொளி எல்.இ.டி பூங்கா & விளையாட்டு மையம்',
  'Chengalpattu',
  'Tirukalukundram',
  'Entertainment',
  ARRAY['LED Illumination', 'Night Park', 'Light Sculptures', 'TTDC Poonga'],
  'Located on East Raja Street inside TTDC Maragatha Poonga in Mamallapuram (Mahabalipuram), Mahabs Glow Garden is a day-to-night theme park featuring thousands of glowing LED sculptures of animals, marine life, and light tunnels.',
  'மகாபலிபுரம் மரகதப் பூங்கா வளாகத்தில் அமைந்துள்ள க்ளோ கார்டன், இரவில் மின்னிமிளிரும் பிரம்மாண்ட எல்.இ.டி விலங்கு உருவங்கள், ஒளி சுரங்கங்கள் கொண்ட இரவு நேரக் பொழுதுபோக்கு பூங்காவாகும்.',
  12.6208000,
  80.1945000,
  'East Raja Street, Maragatha Poonga, Mahabalipuram',
  '603104',
  '10:00 AM - 10:00 PM (Glow illumination active 6 PM - 10 PM)',
  'Year-round (Best after dusk)',
  100.00,
  'Entry ticket per visitor',
  4.60,
  1250,
  'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['glow_garden', 'mahabalipuram', 'mamallapuram', 'ecr', 'led_park'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 15. CHENNAI - THE BEACH TERRACE ECR
(
  'the-beach-terrace-ecr',
  'The Beach Terrace (ECR Santorini Resto-Bar)',
  'தி பீச் டெரஸ் ஈஞ்சம்பாக்கம்',
  'Santorini-inspired oceanfront open-air terrace resto-bar at Injambakkam',
  'ஈஞ்சம்பாக்கம் கடற்கரையில் அமைந்துள்ள சாண்டோரினி பாணி உணவகம்',
  'Chennai',
  'Sholinganallur',
  'Food',
  ARRAY['Oceanfront Dining', 'Resto Bar', 'Santorini Vibe', 'Seafood Grill'],
  'Nestled along the beach front at Injambakkam, East Coast Road, The Beach Terrace is an Aegean-themed open-air destination featuring whitewashed Santorini-style architecture, ocean views, artisanal cocktails, and live seafood grills.',
  'ஈஞ்சம்பாக்கம் இ.சி.ஆர் கடற்கரை ஓரத்தில் கிரேக்கம் சாண்டோரினி பாணி வெள்ளை கட்டிடக்கலை, கடல் காற்று மற்றும் ருசியான உணவுகளுடன் அமைந்த திறந்தவெளி பீச் டெரஸ் உணவகம்.',
  12.8945000,
  80.2525000,
  '5/159, ECR, VGP Salai, Injambakkam, Chennai',
  '600115',
  '12:00 PM - 11:30 PM',
  'Year-round (Best for evening sunset & dinner)',
  0.00,
  'A la carte dining charges apply',
  4.75,
  2400,
  'https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['the_beach_terrace', 'injambakkam', 'ecr', 'santorini', 'sea_view'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 16. CHENNAI - GO XTREME ADVENTURES
(
  'go-xtreme-adventures',
  'Go Xtreme Paintball & Adventure Zone',
  'கோ எக்ஸ்ட்ரீம் பெயிண்ட்பால் & அட்வென்ச்சர்',
  'Outdoor tactical paintball arena, archery & zorbing at Uthandi ECR',
  'உத்தண்டியில் உள்ள பெயிண்ட்பால் மற்றும் சாகச விளையாட்டு மைதானம்',
  'Chennai',
  'Sholinganallur',
  'Adventure',
  ARRAY['Paintball', 'Archery', 'Zorbing', 'Human Foosball', 'Obstacle Course'],
  'Located along the ECR corridor near Uthandi / Sholinganallur, Go Xtreme Adventures is Chennai top outdoor tactical gaming arena featuring speedball/woodball paintball field, archery target shooting, human foosball, and body zorbing.',
  'உத்தண்டி இ.சி.ஆர் பகுதியில் அமைந்துள்ள கோ எக்ஸ்ட்ரீம், நண்பர்களுடன் இணைந்து விளையாடும் பெயிண்ட்பால், வில்வித்தை, பாடி சோர்பிங் மற்றும் சாகச விளையாட்டு வளாகமாகும்.',
  12.8700000,
  80.2400000,
  'Plot No. 18, VGP 2nd Main Road, ECR, Uthandi, Chennai',
  '600119',
  '10:00 AM - 7:30 PM',
  'Year-round',
  500.00,
  'Activity-based pricing & combo packages',
  4.70,
  1650,
  'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['go_xtreme', 'paintball', 'uthandi', 'ecr', 'adventure'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 17. CHENNAI - CHETPET ECO-PARK
(
  'eco-park-chetpet',
  'Chetpet Eco-Park & Sport Fishing Lake',
  'சேத்பட்டு சூழல் பூங்கா & தூண்டில் மீன்பிடி ஏரி',
  '16-acre urban oasis lake with pedal boating, sport fishing & walking track',
  'சேத்பட்டில் 16 ஏக்கர் பரப்பளவில் அமைந்துள்ள ஏரி பூங்கா & படகு சவாரி',
  'Chennai',
  'Egmore',
  'Nature',
  ARRAY['Urban Lake', 'Sport Fishing', 'Boating', 'Walking Track', 'Park'],
  'Situated in central Chennai on Poonamallee High Road, Chetpet Eco-Park is a restored 16-acre urban waterbody maintained by the TN Department of Fisheries. Offers angling and sport fishing, pedal boating, a 1.5 km tree-shaded walking track, and an open-air seafood dining plaza.',
  'பூந்தமல்லி நெடுஞ்சாலையில் சேத்பட்டில் அமைந்துள்ள 16 ஏக்கர் இயற்கை ஏரிப் பூங்கா. படகு சவாரி, தூண்டில் மீன்பிடித்தல், நடைபயிற்சிப் பாதை மற்றும் கடல் உணவு விடுதியைக் கொண்டுள்ளது.',
  13.0742000,
  80.2425000,
  'Poonamallee High Road, Chetpet, Chennai',
  '600031',
  'Walking: 6:00 AM - 9:00 AM & 4:00 PM - 7:00 PM; Boating: 9:00 AM - 6:00 PM',
  'Year-round',
  25.00,
  '₹25 entry fee; separate tickets for boating & fishing',
  4.65,
  5600,
  'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['chetpet_eco_park', 'chetpet_lake', 'boating', 'fishing', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 18. CHENNAI - SANTHOME BEACH
(
  'santhome-beach',
  'Santhome Beach',
  'சாந்தோம் கடற்கரை',
  'Quieter coastal extension of Marina behind historic Santhome Cathedral',
  'வரலாற்றுச் சிறப்புமிக்க சாந்தோம் கதீட்ரல் ஆலயத்தின் பின்புறம் அமைந்த அமைதியான கடற்கரை',
  'Chennai',
  'Mylapore',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Cathedral', 'Quiet Walk'],
  'Santhome Beach is a peaceful, uncrowded sandy stretch tucked directly behind the historic neo-Gothic Santhome Cathedral Basilica. Offers serene ocean views and a calm atmosphere.',
  'சாந்தோம் கதீட்ரல் ஆலயத்திற்குப் பின்னால் அமைந்துள்ள அமைதியான மணற்பரப்பு கொண்ட கடற்கரை.',
  13.0330000,
  80.2780000,
  'Santhome High Road, Mylapore, Chennai',
  '600004',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public entry',
  4.60,
  4100,
  'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['santhome', 'beach', 'mylapore', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 19. CHENNAI - N4 BEACH TONDIARPET
(
  'n4-beach',
  'N4 Beach (Tondiarpet Pier)',
  'என்4 கடற்கரை தண்டையார்பேட்டை',
  'Scenic concrete breakwater pier next to Kasimedu harbour lined with colorful boats',
  'காசிமேடு துறைமுகம் அருகே வண்ணப்படகுகள் நிறைந்த கடற்பாலம் கொண்ட கடற்கரை',
  'Chennai',
  'Tondiarpet',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Pier', 'North Chennai'],
  'Located in Tondiarpet next to Kasimedu harbour, N4 Beach features long concrete groynes stretching into the ocean, colorful fishing boats, crashing waves, and ocean breeze.',
  'தண்டையார்பேட்டையில் காசிமேடு மீன்பிடி துறைமுகத்திற்கு அருகில் அமைந்துள்ள கடற்பாலம் கடற்கரை.',
  13.1210000,
  80.2985000,
  'Kasimedu Coastal Road, Tondiarpet, Chennai',
  '600081',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public access',
  4.60,
  3400,
  'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['n4_beach', 'tondiarpet', 'kasimedu', 'north_chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 20. CHENNAI - THIRUVANMIYUR BEACH
(
  'thiruvanmiyur-beach',
  'Thiruvanmiyur Beach',
  'திருவான்மியூர் கடற்கரை',
  'Tranquil wide golden sand shore favored for morning walks & yoga',
  'காலை நடைபயிற்சி மற்றும் யோகா பயிற்சிகளுக்கு உகந்த திருவான்மியூர் கடற்கரை',
  'Chennai',
  'Velachery',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Yoga', 'Fitness Walk'],
  'Thiruvanmiyur Beach is a spacious, uncrowded residential shoreline south of Besant Nagar. Known for its pristine morning air, gentle tide, and calm atmosphere.',
  'பெசன்ட் நகருக்கு தெற்கே அமைதியான குடியிருப்புப் பகுதியில் அமைந்துள்ள விசாலமான மணற்பரப்பு கொண்ட கடற்கரை.',
  12.9845000,
  80.2640000,
  'Beach Road, Thiruvanmiyur, Chennai',
  '600041',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public access',
  4.70,
  9200,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['thiruvanmiyur', 'beach', 'yoga', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 21. CHENNAI - BREEZY BEACH VALMIKI NAGAR
(
  'breezy-beach',
  'Breezy Beach (Valmiki Nagar)',
  'ப்ரீசி பீச் வால்மீகி நகர்',
  'Small hidden uncrowded coastal pocket in Valmiki Nagar known for serene environment',
  'வால்மீகி நகரில் அமைந்துள்ள அமைதியான அழகிய குடியிருப்பு கடற்கரை',
  'Chennai',
  'Velachery',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Quiet Shore', 'Hidden Gem'],
  'Tucked quietly in Valmiki Nagar, Thiruvanmiyur, Breezy Beach is a clean, tranquil hideaway. Away from commercial street vendors, it offers a peaceful haven for reading and quiet walks.',
  'திருவான்மியூர் வால்மீகி நகரில் சலசலப்பற்ற அமைதியான சூழலில் அமைந்த அழகிய கடற்கரை.',
  12.9810000,
  80.2635000,
  'Valmiki Nagar, Thiruvanmiyur, Chennai',
  '600041',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public access',
  4.80,
  3800,
  'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['breezy_beach', 'valmiki_nagar', 'thiruvanmiyur'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 22. CHENNAI - KOTTIVAKKAM BEACH
(
  'kottivakkam-beach',
  'Kottivakkam Beach',
  'கொட்டிவாக்கம் கடற்கரை',
  'Wide open expanse of clean sand serving as a calm alternative for families on ECR',
  'கிழக்குக் கடற்கரைச் சாலையில் குடும்பத்துடன் செல்ல உகந்த கொட்டிவாக்கம் கடற்கரை',
  'Chennai',
  'Sholinganallur',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Family Friendly', 'ECR'],
  'Kottivakkam Beach features a broad shoreline with soft sand and open ocean vistas. Situated right off the East Coast Road, it provides a quiet setting for family weekend evening walks.',
  'கிழக்குக் கடற்கரைச் சாலையில் குடும்பத்துடன் மாலை நேரத்தில் அமைதியாக உலாவ உகந்த கடற்கரை.',
  12.9680000,
  80.2615000,
  'Clanjung Road, Kottivakkam, Chennai',
  '600041',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public access',
  4.60,
  4500,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['kottivakkam', 'beach', 'ecr', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 23. CHENNAI - PALAVAKKAM BEACH
(
  'palavakkam-beach',
  'Palavakkam Beach',
  'பாலவாக்கம் கடற்கரை',
  'Well-maintained coastal beach with paved walkways & sunrise views',
  'நடைபயிற்சிப் பாதை மற்றும் அமரும் வசதிகள் கொண்ட பாலவாக்கம் கடற்கரை',
  'Chennai',
  'Sholinganallur',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Paved Walkway', 'Sunset View'],
  'Palavakkam Beach is popular for its neat paved walking track, manicured seating benches, and wide open horizon views. Ideal for evening family strolls.',
  'நடைபயிற்சிப் பாதை மற்றும் பெஞ்சுகள் அமைக்கப்பட்ட தூய்மையான பாலவாக்கம் கடற்கரை.',
  12.9554000,
  80.2592000,
  'Palavakkam Beach Road, Palavakkam, Chennai',
  '600041',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public access',
  4.70,
  6200,
  'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['palavakkam', 'beach', 'ecr', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 24. CHENNAI - NEELANKARAI BEACH
(
  'neelankarai-beach',
  'Neelankarai Beach',
  'நீலாங்கரை கடற்கரை',
  'Peaceful beach serving as an active nesting ground for Olive Ridley sea turtles',
  'ஆலிவ் ரிட்லி கடலாமைகள் முட்டையிடும் இடமாக விளங்கும் நீலாங்கரை கடற்கரை',
  'Chennai',
  'Sholinganallur',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Turtle Nesting', 'Nature Conservation'],
  'Neelankarai Beach is a pristine coastal strip along ECR. Famous among nature lovers as a key annual nesting ground for Olive Ridley sea turtles (Jan–April).',
  'இயற்கை விரும்பிகளால் விரும்பப்படும் ஆலிவ் ரிட்லி ஆமைகள் முட்டையிடும் அமைதியான கடற்கரை.',
  12.9440000,
  80.2580000,
  'Kapaleeswarar Nagar, Neelankarai, Chennai',
  '600115',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public access',
  4.70,
  5100,
  'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['neelankarai', 'beach', 'turtle_nesting', 'ecr'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 25. CHENNAI - AKKARAI BEACH
(
  'akkarai-beach',
  'Akkarai Beach',
  'அக்கரை கடற்கரை',
  'Clean sands, minimal noise & manicured green approach pathways',
  'பச்சை பசேல் பாதைகள் மற்றும் குறைந்த சலசலப்பு கொண்ட அக்கரை கடற்கரை',
  'Chennai',
  'Sholinganallur',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Green Pathways', 'Quiet Shore'],
  'Situated near the Akkarai junction on ECR, Akkarai Beach is renowned for its clean shoreline, landscaped lawn approaches, and quiet coastal air.',
  'அக்கரை சந்திப்பு அருகே பசுமையான அணுகுபாதைகளுடன் அமைந்துள்ள அழகிய கடற்கரை.',
  12.9280000,
  80.2560000,
  'Akkarai Beach Road, Injambakkam, Chennai',
  '600119',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public access',
  4.60,
  3900,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['akkarai', 'beach', 'ecr', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 26. CHENNAI - INJAMBAKKAM BEACH
(
  'injambakkam-beach',
  'Injambakkam Beach',
  'இஞ்சம்பாக்கம் கடற்கரை',
  'Spacious quiet beach ideal for solitary walks & coastal views',
  'இஞ்சம்பாக்கத்தில் அமைந்துள்ள விசாலமான அமைதியான கடற்கரை',
  'Chennai',
  'Sholinganallur',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Quiet Trail', 'Solitary Walk'],
  'Injambakkam Beach is a secluded coastal stretch featuring wide sandy shores, coastal palm trees, and gentle surf. Ideal for peaceful walks.',
  'இஞ்சம்பாக்கம் பகுதியில் பனைமரங்கள் மற்றும் மென்மையான அலைகள் கொண்ட அமைதியான கடற்கரை.',
  12.9100000,
  80.2550000,
  'Prarthana Drive, Injambakkam, Chennai',
  '600119',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public access',
  4.70,
  4800,
  'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['injambakkam', 'beach', 'ecr', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 27. CHENNAI - UTHANDI BEACH
(
  'uthandi-beach',
  'Uthandi Beach',
  'உத்தண்டி கடற்கரை',
  'Pristine private beach lane accessed through quiet residential neighborhood',
  'உத்தண்டி குடியிருப்பு பகுதியில் அமைந்துள்ள தூய்மையான பிரைவேட் கடற்கரை',
  'Chennai',
  'Sholinganallur',
  'Beaches',
  ARRAY['Beach', 'Coastal', 'Pristine Shore', 'Residential'],
  'Located at the southern limit of Chennai district along ECR, Uthandi Beach is a pristine, hidden coastal avenue surrounded by quiet residential enclaves.',
  'சென்னை மாவட்டத்தின் தெற்கு எல்லையில் உத்தண்டியில் அமைந்துள்ள தூய்மையான கடற்கரை.',
  12.8720000,
  80.2460000,
  'Uthandi Toll / Beach Road, Uthandi, Chennai',
  '600119',
  'Open 24/7',
  'November to February',
  0.00,
  'Free public access',
  4.80,
  2900,
  'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['uthandi', 'beach', 'ecr', 'chennai'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 28. CHENNAI - VGP GOLDEN BEACH
(
  'vgp-golden-beach',
  'VGP Golden Beach',
  'விஜிபி கோல்டன் பீச்',
  'Private well-maintained beach integrated with VGP amusement park',
  'விஜிபி பொழுதுபோக்கு பூங்காவுடன் இணைக்கப்பட்ட குடும்பக் கடற்கரை',
  'Chennai',
  'Sholinganallur',
  'Beaches',
  ARRAY['Beach', 'Amusement Park', 'Family Outing', 'Managed Beach'],
  'VGP Golden Beach in Injambakkam is one of Chennai oldest managed beach park destinations featuring clean sands, sculptures, and safe family beach access.',
  'விஜிபி பொழுதுபோக்கு பூங்காவின் ஒரு பகுதியாக அமைந்துள்ள பாதுகாப்பான குடும்பக் கடற்கரை.',
  12.9145000,
  80.2522000,
  'East Coast Road, Injambakkam, Chennai',
  '600119',
  '9:30 AM - 6:30 PM',
  'Year-round',
  350.00,
  'Ticketed entry pass',
  4.70,
  18900,
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['vgp_golden_beach', 'vgp', 'injambakkam', 'ecr'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 29. CHENGALPATTU - MUTTUKADU BEACH
(
  'muttukadu-beach',
  'Muttukadu Beach & Backwaters',
  'முட்டுக்காடு கடற்கரை & காயல்',
  'Picturesque estuary where backwaters meet the sea with boat house & watersports',
  'கடலும் காயலும் சங்கமிக்கும் முட்டுக்காடு படகு குழாம் கடற்கரை',
  'Chengalpattu',
  'Thiruporur',
  'Beaches',
  ARRAY['Beach', 'Estuary', 'Boating', 'Watersports', 'Backwaters'],
  'Situated 30 km south of Chennai on ECR, Muttukadu Beach sits where Kovalam backwaters meet the Bay of Bengal. Features TTDC boat house with pedal boating & speedboats.',
  'இ.சி.ஆர் சாலையில் கடலும் காயலும் சங்கமிக்கும் அழகிய முட்டுக்காடு படகு குழாம் கடற்கரை.',
  12.8250000,
  80.2440000,
  'East Coast Road, Muttukadu, Tamil Nadu',
  '603112',
  '9:00 AM - 6:00 PM',
  'November to March',
  50.00,
  'Ticketed boating sessions',
  4.60,
  14200,
  'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['muttukadu', 'beach', 'boating', 'ecr'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 30. CHENGALPATTU - MAHABALIPURAM BEACH
(
  'mahabalipuram-beach',
  'Mahabalipuram Beach (Mamallapuram)',
  'மாமல்லபுரம் கடற்கரை',
  'Historic coastal getaway with UNESCO 7th-century Shore Temple backdrop',
  'யுனெஸ்கோ கடற்கரைக் கோவில் பின்னணியில் அமைந்த மாமல்லபுரம் கடற்கரை',
  'Chengalpattu',
  'Tirukalukundram',
  'Beaches',
  ARRAY['Beach', 'UNESCO Heritage', 'Shore Temple', 'Seafood', 'Coastal'],
  'Located 55 km south of Chennai, Mahabalipuram Beach combines coastal beauty with 7th-century Pallava Shore Temple architecture overlooking crashing waves.',
  '7-ஆம் நூற்றாண்டு பல்லவர் கால கடற்கரைக் கோவிலின் பின்னணியில் அமைந்த உலகப் புகழ்பெற்ற மாமல்லபுரம் கடற்கரை.',
  12.6180000,
  80.1980000,
  'Beach Road, Mamallapuram, Tamil Nadu',
  '603104',
  'Open 24/7',
  'October to March',
  0.00,
  'Free beach access; ASI ticket for Shore Temple',
  4.90,
  58000,
  'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['mahabalipuram', 'beach', 'shore_temple', 'unesco', 'ecr'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 26. PANCHA BHOOTA 1: EKAMBARESWARAR TEMPLE (EARTH - PRITHVI)
(
  'ekambareswarar-temple',
  'Ekambareswarar Temple',
  'ஏகாம்பரேஸ்வரர் திருக்கோவில் (நிலம் - பிருத்வி ஸ்தலம்)',
  'Pancha Bhoota Prithvi (Earth) Stalam with 3,500-Year Sacred Mango Tree & Sand Lingam',
  'பஞ்ச பூத தலங்களில் நிலத்தைக் குறிக்கும் பிருத்வி ஸ்தலம் மற்றும் 3,500 ஆண்டுகள் பழமையான மாமரம்',
  'Kancheepuram',
  'Kanchipuram',
  'Temple',
  ARRAY['Pancha Bhoota', 'Spiritual', 'Dravidian Architecture', 'Heritage', 'Shiva Stalam'],
  'One of the five sacred Pancha Bhoota Sthalams representing the Earth element (Prithvi). Revered for the Prithvi Lingam sculpted from sand by Goddess Parvati beneath a sacred mango tree. Features an imposing 59-meter tall 11-tier Southern Rajagopuram built by King Krishnadevaraya in 1509 CE and a 1,000-pillared hall.',
  'பஞ்ச பூத தலங்களில் நிலத்தைக் குறிக்கும் திருத்தலம். அன்னை பார்வதி தேவி மணலால் பிடித்த சிவலிங்கம் (பிருத்வி லிங்கம்) மற்றும் வேதங்களை உணர்த்தும் 3,500 ஆண்டுகள் பழமையான புனித மாமரம் இங்குள்ளது. கிருஷ்ணதேவராயரால் கட்டப்பட்ட 192 அடி உயர ராஜகோபுரம் கொண்டது.',
  12.8475000,
  79.6997000,
  'Sannathi Street, Periya Kanchipuram, Tamil Nadu',
  '631502',
  '6:00 AM - 12:30 PM, 4:00 PM - 8:30 PM',
  'October to March (Panguni Uthiram in March/April)',
  0.00,
  'Free general entry',
  4.90,
  2840,
  'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['temple', 'pancha_bhoota', 'earth', 'prithvi', 'kanchipuram', 'shiva'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 27. PANCHA BHOOTA 2: JAMBUKESWARAR TEMPLE (WATER - APPU)
(
  'jambukeswarar-temple',
  'Jambukeswarar Temple',
  'ஜம்புகேஸ்வரர் திருக்கோவில் (நீர் - அப்பு ஸ்தலம்)',
  'Pancha Bhoota Appu (Water) Stalam with Perennial Underground Spring in Sanctum',
  'பஞ்ச பூத தலங்களில் நீரைக் குறிக்கும் அப்பு ஸ்தலம் மற்றும் கருவறையில் வற்றாத ஊற்று நீர்',
  'Tiruchirappalli',
  'Thiruvanaikaval',
  'Temple',
  ARRAY['Pancha Bhoota', 'Spiritual', 'Chola Architecture', 'Heritage', 'Shiva Stalam'],
  'Revered Pancha Bhoota Sthalam representing the Water element (Appu), situated in Thiruvanaikaval on Srirangam island. An underground perennial natural spring flows continuously beneath the Shiva Lingam in the inner sanctum, keeping it submerged in holy water throughout the year. Built by Early Chola King Kochengannan over 1,800 years ago.',
  'பஞ்ச பூத தலங்களில் நீரைக் குறிக்கும் அப்பு திருத்தலம். காவிரியின் உபநதியான கொள்ளிடத்தின் அருகே திருவானைக்காவலில் அமைந்துள்ளது. கருவறை லிங்கத்தின் அடியில் எப்போதும் வற்றாத இயற்கை ஊற்று நீர் பிரவகித்துக் கொண்டிருக்கிறது.',
  10.8534000,
  78.7054000,
  'Sannathi Street, Thiruvanaikaval, Tiruchirappalli, Tamil Nadu',
  '620005',
  '5:30 AM - 1:00 PM, 3:00 PM - 9:00 PM',
  'October to March',
  0.00,
  'Free general entry',
  4.85,
  2310,
  'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['temple', 'pancha_bhoota', 'water', 'appu', 'tiruchirappalli', 'thiruvanaikaval', 'shiva'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 28. PANCHA BHOOTA 3: ARUNACHALESWARAR TEMPLE (FIRE - AGNI)
(
  'arunachaleswarar-temple',
  'Arunachaleswarar Temple',
  'அருணாசலேஸ்வரர் திருக்கோவில் (நெருப்பு - தேயு ஸ்தலம்)',
  'Pancha Bhoota Agni (Fire) Stalam & 14km Arunachala Giri Pradakshina Hill Circuit',
  'பஞ்ச பூத தலங்களில் நெருப்பைக் குறிக்கும் அக்னி ஸ்தலம் மற்றும் 14 கி.மீ கிரிவலப் பாதை',
  'Tiruvannamalai',
  'Tiruvannamalai',
  'Temple',
  ARRAY['Pancha Bhoota', 'Spiritual', 'Dravidian Architecture', 'Giri Valam', 'Shiva Stalam'],
  'The magnificent Agni Stalam of the Pancha Bhoota representing the Fire element, standing at the base of sacred Arunachala Hill. Sprawls over 25 acres with four imposing Rajagopurams, including the 217-foot Eastern tower. Famous for the 14-km barefoot Giri Pradakshina circumambulation and the legendary Karthigai Deepam beacon lit atop Arunachala peak.',
  'பஞ்ச பூத தலங்களில் நெருப்பைக் குறிக்கும் அக்னி தலம். அருணாசல மலையின் அடிவாரத்தில் 25 ஏக்கர் பரப்பளவில் அமைந்துள்ள பிரம்மாண்ட கோவில். 14 கி.மீ கிரிவலப் பாதையும், கார்த்திகை தீபத் திருவிழாவில் மலை உச்சியில் ஏற்றப்படும் மகா தீபமும் உலகப் புகழ்பெற்றவை.',
  12.2319000,
  79.0677000,
  'Pavazhakundur, Tiruvannamalai, Tamil Nadu',
  '606601',
  '5:30 AM - 12:30 PM, 3:30 PM - 9:30 PM',
  'October to March (Karthigai Deepam in Nov/Dec)',
  0.00,
  'Free general entry',
  4.95,
  5200,
  'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['temple', 'pancha_bhoota', 'fire', 'agni', 'tiruvannamalai', 'arunachala', 'shiva'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 29. PANCHA BHOOTA 4: SRIKALAHASTEESWARA TEMPLE (AIR - VAYU)
(
  'srikalahasteeswara-temple',
  'Srikalahasteeswara Temple',
  'ஸ்ரீகாளஹஸ்தீஸ்வரர் திருக்கோவில் (காற்று - வாயு ஸ்தலம்)',
  'Pancha Bhoota Vayu (Air) Stalam with Flickering Sanctum Lamp & Rahu-Ketu Kshetram',
  'பஞ்ச பூத தலங்களில் காற்றைக் குறிக்கும் வாயு ஸ்தலம் மற்றும் ராகு-கேது பரிகார தலம்',
  'Tirupati',
  'Srikalahasti',
  'Temple',
  ARRAY['Pancha Bhoota', 'Spiritual', 'Chola Architecture', 'Rahu Ketu Kshetram', 'Shiva Stalam'],
  'The ancient Vayu Stalam of the Pancha Bhoota representing the Air element, situated on the banks of the Swarnamukhi River bordering northern Tamil Nadu. Inside the airtight inner sanctum devoid of breeze, the flame of the sacred lamp continuously flickers, confirming the presence of the Air Lingam. Renowned worldwide for Rahu-Ketu Sarpa Dosha Nivarana pujas.',
  'பஞ்ச பூத தலங்களில் காற்றைக் குறிக்கும் வாயு திருத்தலம். சுவர்ணமுகி நதிக்கரையில் அமைந்துள்ளது. காற்று புக முடியாத கருவறையிலும் தீபம் எப்போதும் காற்றில் அசைந்தாடுவது இதன் விசேஷ அற்புதம். உலகப் புகழ்பெற்ற ராகு-கேது சர்ப்ப தோஷ நிவர்த்தி தலம்.',
  13.7498000,
  79.6984000,
  'Srikalahasti, Tirupati District, Andhra Pradesh',
  '517644',
  '6:00 AM - 9:00 PM Continuous',
  'September to March (Maha Shivaratri in Feb/March)',
  0.00,
  'Free general entry',
  4.85,
  3600,
  'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['temple', 'pancha_bhoota', 'air', 'vayu', 'srikalahasti', 'shiva'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 30. PANCHA BHOOTA 5: THILLAI NATARAJA TEMPLE (SPACE - AKASHA)
(
  'chidambaram-nataraja-temple',
  'Thillai Nataraja Temple',
  'தில்லை நடராஜர் திருக்கோவில் (ஆகாயம் - ஆகாய ஸ்தலம்)',
  'Pancha Bhoota Akasha (Space) Stalam with Gold-Tiled Chit Sabha & Chidambara Rahasyam',
  'பஞ்ச பூத தலங்களில் ஆகாயத்தைக் குறிக்கும் ஸ்தலம், பொற்சபை மற்றும் சிதம்பர ரகசியம்',
  'Cuddalore',
  'Chidambaram',
  'Temple',
  ARRAY['Pancha Bhoota', 'Spiritual', 'Chola Architecture', 'Chidambara Rahasyam', 'Shiva Stalam'],
  'The supreme Akasha Stalam representing the Space (Ether) element where Lord Shiva is worshipped as Nataraja performing the cosmic dance (Ananda Tandava). Famous for the Chidambara Rahasyam (secret of formless infinite space behind golden bilva leaves), the 21,600 gold tiles on the Chit Sabha roof representing human breaths, and the 108 Bharatanatyam dance postures carved in stone.',
  'பஞ்ச பூத தலங்களில் ஆகாயத்தைக் குறிக்கும் சிதம்பரம் நடராஜர் திருக்கோவில். சிவபெருமான் ஆனந்த தாண்டவக் கோலத்தில் காட்சியளிக்கிறார். 21,600 தங்க ஓடுகளால் வேயப்பட்ட பொற்சபை, 108 பரதநாட்டிய கரணங்கள் மற்றும் அருவமான இறைநிலையை உணர்த்தும் சிதம்பர ரகசியம் இதன் சிறப்புகள்.',
  11.3992000,
  79.6934000,
  'East Car Street, Chidambaram, Tamil Nadu',
  '608001',
  '6:00 AM - 12:00 PM, 5:00 PM - 10:00 PM',
  'October to March (Natyanjali Dance Festival in Feb/March)',
  0.00,
  'Free general entry',
  4.92,
  4100,
  'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80',
  ARRAY['https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80'],
  ARRAY['temple', 'pancha_bhoota', 'space', 'akasha', 'chidambaram', 'nataraja', 'shiva'],
  TRUE,
  TRUE,
  'public',
  'published'
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  tamil_name = EXCLUDED.tamil_name,
  tagline = EXCLUDED.tagline,
  tamil_tagline = EXCLUDED.tamil_tagline,
  district = EXCLUDED.district,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  tamil_description = EXCLUDED.tamil_description,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  opening_hours = EXCLUDED.opening_hours,
  rating = EXCLUDED.rating,
  image_url = EXCLUDED.image_url,
  status = EXCLUDED.status,
  visibility = EXCLUDED.visibility,
  updated_at = NOW();
