-- ========================================================================
-- ExploreTN — Tamil Nadu Structured Places Seed Dataset
-- Rich Tamil & English canonical destinations with exact spatial coordinates
-- ========================================================================

INSERT INTO public.places (
  slug, name, tamil_name, tagline, tamil_tagline, district, taluk, category, subcategories,
  description, tamil_description, latitude, longitude, address, pincode, opening_hours,
  best_time_to_visit, entry_fee_inr, entry_fee_info, rating, review_count, image_url, gallery_urls,
  tags, is_featured, is_verified, visibility, status
) VALUES
-- 1. MADURAI - MEENAKSHI AMMAN TEMPLE
(
  'meenakshi-amman-temple-madurai',
  'Meenakshi Amman Temple',
  'மீனாட்சி அம்மன் கோவில்',
  'Historic Dravidian masterpiece with 14 towering gopurams',
  '14 பிரம்மாண்ட கோபுரங்கள் கொண்ட திராவிடக் கட்டிடக்கலை அற்புதம்',
  'Madurai',
  'Madurai North',
  'Temple',
  ARRAY['Dravidian Architecture', 'Spiritual', 'Heritage', 'UNESCO Nominee'],
  'The crown jewel of Madurai, dedicated to Goddess Meenakshi and Lord Sundareswarar. Features 14 towering gopurams decorated with thousands of painted stone figures, the 1,000-pillared hall (Aayiram Kaal Mandapam), and the sacred Golden Lotus Tank (Pottramarai Kulam).',
  'மதுரையின் திலகமாக விளங்கும் உலகப் புகழ்பெற்ற மீனாட்சி சுந்தரேஸ்வரர் திருக்கோவில். 14 வண்ணமயமான கோபுரங்கள், ஆயிரம் கால் மண்டபம் மற்றும் பொற்றாமரைக் குளம் கொண்ட வரலாற்றுச் சிறப்புமிக்க ஆன்மீக மையம்.',
  9.9195000,
  78.1193000,
  'Madurai Main, Town Hall Road, Madurai',
  '625001',
  '5:00 AM - 12:30 PM, 4:00 PM - 9:30 PM',
  'October to March (Chithirai Thiruvizha in April)',
  0.00,
  'Free entry for temple main complex',
  4.95,
  12450,
  '/assets/places/meenakshi-amman.jpg',
  ARRAY['/assets/places/meenakshi-gopuram.jpg', '/assets/places/meenakshi-tank.jpg'],
  ARRAY['temple', 'madurai', 'dravidian', 'gopuram', 'heritage'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 2. MADURAI - PUTHU MANDAPAM
(
  'puthu-mandapam-thrift-market-madurai',
  'Puthu Mandapam Ancient Thrift Bazaar',
  'புது மண்டபம் ஆடை தைப்பகம் & பாரம்பரிய கடைத்தெரு',
  '400-year-old pillared tailoring hall and artisan silk bazaar',
  '400 ஆண்டுகள் பழமையான கல்தூண் மண்டப தையல் கலைக்கடைகள்',
  'Madurai',
  'Madurai South',
  'Thrift Street',
  ARRAY['Tailoring', 'Handloom', 'Silk', 'Brassware', 'Heritage Market'],
  'Constructed by King Thirumalai Nayak in 1635 directly opposite the East Gopuram. Home to over 150 vintage sewing machines, heritage tailors, silk merchants, and brassware artisans working inside historic stone carved pillars.',
  'திருமலை நாயக்கரால் 1635-இல் கட்டப்பட்ட வரலாற்றுச் சிறப்புமிக்க கல்தூண் மண்டபம். கிழக்கு கோபுரத்தின் எதிரே தையல் கலைஞர்கள், பட்டு வியபாரிகள் மற்றும் பித்தளைக் கைவினைஞர்களின் வரலாற்றுச் சந்தை.',
  9.9198000,
  78.1210000,
  'Opposite East Tower, Meenakshi Temple Street, Madurai',
  '625001',
  '9:30 AM - 9:00 PM',
  'All Year Round',
  0.00,
  'Free Entry',
  4.85,
  3890,
  '/assets/places/puthu-mandapam.jpg',
  ARRAY['/assets/places/puthu-mandapam-tailors.jpg'],
  ARRAY['thrift', 'madurai', 'bazaar', 'heritage', 'silk'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 3. MADURAI - FAMOUS JIGARTHANDA
(
  'famous-jigarthanda-town-hall-road-madurai',
  'Famous Jigarthanda (Town Hall Road)',
  'ஃபேமஸ் ஜிகர்தண்டா (டவுன் ஹால் ரோடு)',
  'Madura''s signature cooling drink made with almond gum and basundi',
  'மதுரையின் பெருமைமிகு பாதாம் பிசின் & பாசந்தி குளிர் பானம்',
  'Madurai',
  'Madurai Central',
  'Food Spot',
  ARRAY['Street Food', 'Beverage', 'Dessert', 'Iconic Taste'],
  'The authentic home of Jigarthanda (meaning "Heart Cooler"). Prepared using organic badam pisin (almond gum), nannari sarsaparilla syrup, reduced caramelized milk, and topped with rich homemade basundi ice cream.',
  'மதுரையின் இதயம் குளிர்ந்த பானம்! இயற்கை பாதாம் பிசின், நன்னாரி சர்பத், சுண்டக்காய்ச்சிய பால் மற்றும் பிரத்யேக பாசந்தி ஐஸ்கிரீம் கலந்த சுவையான குளிர்பானம்.',
  9.9160000,
  78.1140000,
  '14, Town Hall Road, Madurai',
  '625001',
  '10:00 AM - 11:00 PM',
  'All Year Round (Best in Summer)',
  80.00,
  '₹80 (Special) / ₹120 (Super Special)',
  4.90,
  8210,
  '/assets/places/jigarthanda.jpg',
  ARRAY['/assets/places/jigarthanda-glass.jpg'],
  ARRAY['food', 'madurai', 'jigarthanda', 'street-food', 'dessert'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 4. THANJAVUR - BRIHADEESWARAR TEMPLE (BIG TEMPLE)
(
  'brihadeeswarar-temple-thanjavur',
  'Brihadeeswarar Temple (Thanjavur Big Temple)',
  'தஞ்சாவூர் பிரகதீஸ்வரர் கோவில் (பெரிய கோவில்)',
  '1,000-year-old Chola architectural wonder & UNESCO World Heritage site',
  'சோழப் பேரரசின் 1000 ஆண்டுகள் பழமையான யுனெஸ்கோ உலகப் பாரம்பரியச் சின்னம்',
  'Thanjavur',
  'Thanjavur North',
  'Heritage',
  ARRAY['UNESCO World Heritage', 'Chola Architecture', 'Granite Monolith', 'Spiritual'],
  'Built by Emperor Raja Raja Chola I in 1010 AD. Known for its 216-ft vimana hollow tower made entirely of interlocking granite, single-stone 80-ton Kumbam cap, and giant Nandi monolith.',
  'முதலாம் இராஜராஜ சோழனால் கி.பி 1010-இல் கட்டப்பட்ட கட்டடக் கலை அற்புதம். 216 அடி உயர கருங்கல் விமானம் மற்றும் 80 டன் எடையுள்ள ஒரே கல் சிகரம் கொண்ட உலகப் புகழ்பெற்ற கோவில்.',
  10.7828000,
  79.1318000,
  'Membalam Road, Balaganapathy Nagar, Thanjavur',
  '613007',
   meenakshi -> '6:00 AM - 12:30 PM, 4:00 PM - 8:30 PM',
  'October to March',
  0.00,
  'Free Entry (Archaeological Survey of India maintained)',
  4.97,
  15200,
  '/assets/places/thanjavur-big-temple.jpg',
  ARRAY['/assets/places/thanjavur-nandi.jpg', '/assets/places/thanjavur-tower.jpg'],
  ARRAY['thanjavur', 'chola', 'unesco', 'big-temple', 'heritage'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 5. NILGIRIS - OOTY BOTANICAL GARDENS & SHOLA PASS
(
  'government-botanical-garden-ooty',
  'Government Botanical Garden Ooty',
  'அரசு தாவரவியல் பூங்கா உதகமண்டலம்',
  '55-acre high-altitude flora paradise established in 1848',
  'நீலகிரி மலையில் 55 ஏக்கரில் அமைந்துள்ள 175 ஆண்டுகள் பழமையான தாவரவியல் பூங்கா',
  'Nilgiris',
  'Udhagamandalam',
  'Hill Station',
  ARRAY['Nature', 'Flora', 'High Altitude', 'Fossil Tree'],
  'Laid out in 1848 on the slopes of Doddabetta peak. Features over 1,000 species of exotic plants, a 20-million-year-old fossilized tree trunk, Italian garden terracing, and vibrant annual flower shows.',
  '1848-இல் தொட்டபெட்டா சிகரச் சரிவில் அமைக்கப்பட்ட எழில்மிகு தாவரவியல் பூங்கா. 1000-க்கும் மேற்பட்ட அபூர்வ தாவரங்கள் மற்றும் 2 கோடி ஆண்டுகள் பழமையான மரப் படிமம் கொண்ட இயற்கை சொர்க்கம்.',
  11.4167000,
  76.7117000,
  'Vanguard Road, Udhagamandalam, Nilgiris',
  '643001',
  '7:00 AM - 6:30 PM',
  'September to May',
  40.00,
  '₹40 (Adults) / ₹20 (Children) / ₹50 (Still Camera)',
  4.82,
  9400,
  '/assets/places/ooty-botanical-garden.jpg',
  ARRAY['/assets/places/ooty-flowers.jpg'],
  ARRAY['ooty', 'nilgiris', 'hill-station', 'botanical-garden', 'nature'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 6. MAHABALIPURAM - SHORE TEMPLE & SHORELINE MONUMENTS
(
  'shore-temple-mahabalipuram',
  'Shore Temple & Monolithic Rathas',
  'மாமல்லபுரம் கடற்கரைக் கோவில் & பஞ்ச ரதங்கள்',
  '7th-century Pallava coastal rock-cut temples facing the Bay of Bengal',
  'பல்லவ மன்னர்களின் 7-ஆம் நூற்றாண்டு வங்காள விரிகுடா கடற்கரை குடைவரைக் கோவில்கள்',
  'Chengalpattu',
  'Tirukalukundram',
  'Heritage',
  ARRAY['UNESCO World Heritage', 'Pallava Dynasty', 'Rock-cut Architecture', 'Coastal'],
  'Built during the reign of King Narasimhavarman II (700–728 AD). Perched on the edge of the Bay of Bengal, featuring 5 monolithic Pancha Rathas carved from single boulders and Arjuna''s Penance bas-relief.',
  'கி.பி 8-ஆம் நூற்றாண்டில் நரசிம்மவர்மன் காலத்தில் கட்டப்பட்ட யுனெஸ்கோ உலகப் பாரம்பரிய கடற்கரைக் கோவில். பஞ்ச ரதங்கள் மற்றும் அர்ஜுனன் தபசு பாறைச் சிற்பங்கள் கொண்ட பல்லவ கலைக் கூடம்.',
  12.6163000,
  80.1983000,
  'Shore Temple Road, Mahabalipuram, Chengalpattu',
  '603104',
  '6:00 AM - 6:00 PM',
  'October to March',
  40.00,
  '₹40 for Indian Citizens / ₹600 for Foreign Tourists',
  4.91,
  11300,
  '/assets/places/shore-temple.jpg',
  ARRAY['/assets/places/pancha-rathas.jpg'],
  ARRAY['mahabalipuram', 'pallava', 'unesco', 'beach', 'heritage'],
  TRUE,
  TRUE,
  'public',
  'published'
),

-- 7. KANYAKUMARI - VIVEKANANDA ROCK MEMORIAL & THIRUVALLUVAR STATUE
(
  'vivekananda-rock-memorial-kanyakumari',
  'Vivekananda Rock Memorial & Thiruvalluvar Statue',
  'விவேகானந்தர் பாறை நினைவாலயம் & திருவள்ளுவர் சிலை',
  'Confluence of three oceans where Swami Vivekananda meditated',
  'முக்கடல் சங்கமத்தில் அமைந்துள்ள 133 அடி திருவள்ளுவர் சிலை & விவேகானந்தர் பாறை',
  'Kanyakumari',
  'Agastheeswaram',
  'Heritage',
  ARRAY['Triveni Sangam', 'Monuments', 'Islet', 'Ocean View'],
  'Standing on a rock island 500 meters off the coast of Triveni Sangam (confluence of Indian Ocean, Arabian Sea, and Bay of Bengal). Features the 133-ft stone Thiruvalluvar statue representing the 133 chapters of Thirukkural.',
  'முக்கடலும் சந்திக்கும் முனைக்கு 500 மீட்டர் தொலைவில் அமைந்துள்ள விவேகானந்தர் பாறை மற்றும் 133 அதிகாரங்களைக் குறிக்கும் 133 அடி உயரப் பிரம்மாண்ட திருவள்ளுவர் சிலை.',
  8.0781000,
  77.5554000,
  'Sunset Point Road, Kanyakumari',
  '629702',
  '8:00 AM - 4:00 PM',
  'October to March',
  50.00,
  '₹50 Ferry ticket + ₹20 Entry ticket',
  4.94,
  14100,
  '/assets/places/vivekananda-rock.jpg',
  ARRAY['/assets/places/thiruvalluvar-statue.jpg'],
  ARRAY['kanyakumari', 'thiruvalluvar', 'sangam', 'ocean', 'monument'],
  TRUE,
  TRUE,
  'public',
  'published'
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  tamil_name = EXCLUDED.tamil_name,
  tagline = EXCLUDED.tagline,
  tamil_tagline = EXCLUDED.tamil_tagline,
  district = EXCLUDED.district,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  tamil_description = EXCLUDED.tamil_description,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  opening_hours = EXCLUDED.opening_hours,
  rating = EXCLUDED.rating,
  image_url = EXCLUDED.image_url,
  status = EXCLUDED.status,
  visibility = EXCLUDED.visibility,
  updated_at = NOW();
