import { defineEventHandler, getQuery } from "h3";

const MASTER_SERVER_PLACES: any[] = [
  { id: 'p-marina-beach', slug: 'marina-beach', name: 'Marina Beach', display_name: 'Marina Beach, Chennai', type: 'BEACH', category: 'coastal', subcategory: 'beach', tagline: 'Second longest natural urban beach in the world', description: 'A 13km natural urban beach along the Bay of Bengal in Chennai, famous for sunrise views, street food stalls, and lighthouse.', latitude: 13.0499, longitude: 80.2824, city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', country: 'India', region: 'Coromandel Coast', aliases: ['marina', 'marina beach', 'chennai marina'], activities: ['beaches', 'street_food', 'walking'], tags: ['beach', 'urban', 'coastal'], image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80', rating: 4.7, verified: true },
  { id: 'p-kapaleeshwarar-temple', slug: 'kapaleeshwarar-temple', name: 'Kapaleeshwarar Temple', display_name: 'Kapaleeshwarar Temple, Mylapore', type: 'TEMPLE', category: 'temple', subcategory: 'heritage', tagline: '7th-century Dravidian Shiva shrine in historical Mylapore', description: 'An ancient temple dedicated to Lord Shiva in Mylapore, Chennai, built in classic Dravidian architecture.', latitude: 13.0335, longitude: 80.2697, city: 'Mylapore', district: 'Chennai', state: 'Tamil Nadu', country: 'India', region: 'Mylapore Heritage Zone', aliases: ['kapaleeshwarar', 'mylapore temple'], activities: ['temples', 'heritage'], tags: ['temple', 'dravidian', 'shiva'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 4.8, verified: true },
  { id: 'p-shore-temple', slug: 'shore-temple', name: 'Shore Temple', display_name: 'Shore Temple, Mahabalipuram', type: 'HERITAGE_SITE', category: 'heritage', subcategory: 'temple', tagline: '8th-century Pallava structural stone temple on the Coromandel coast', description: 'UNESCO World Heritage structural stone temple complex built by King Narasimhavarman II overlooking the Bay of Bengal.', latitude: 12.616, longitude: 80.1989, city: 'Mahabalipuram', district: 'Chengalpattu', state: 'Tamil Nadu', country: 'India', region: 'Coromandel Coast', aliases: ['shore temple', 'mahabalipuram shore temple'], activities: ['heritage', 'photography'], tags: ['unesco', 'pallava', 'heritage'], image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80', rating: 4.9, verified: true },
  { id: 'p-kailasanathar-temple', slug: 'kailasanathar-temple', name: 'Kailasanathar Temple', display_name: 'Kailasanathar Temple, Kancheepuram', type: 'TEMPLE', category: 'temple', subcategory: 'heritage', tagline: 'Oldest sandstone structural temple in Kancheepuram', description: 'Constructed in 685–705 AD, this is the oldest surviving sandstone structure in Kancheepuram.', latitude: 12.8423, longitude: 79.6898, city: 'Kancheepuram', district: 'Kancheepuram', state: 'Tamil Nadu', country: 'India', region: 'Northern Tamil Nadu', aliases: ['kanchi kailasanathar'], activities: ['temples', 'heritage'], tags: ['sandstone', 'pallava'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 4.8, verified: true },
  { id: 'p-yelagiri-hills', slug: 'yelagiri-hills', name: 'Yelagiri Hills', display_name: 'Yelagiri Hills, Tirupattur', type: 'HILL', category: 'mountain', subcategory: 'viewpoint', tagline: 'Peaceful hill cluster at 1,110m MSL with Punganoor Lake', description: 'A tranquil hill station comprising 14 tribal hamlets surrounded by rose gardens and orchards.', latitude: 12.5804, longitude: 78.6385, city: 'Yelagiri', district: 'Tirupattur', state: 'Tamil Nadu', country: 'India', region: 'Eastern Ghats', aliases: ['yelagiri'], activities: ['trekking', 'boating'], tags: ['hill_station', 'lake'], image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80', rating: 4.6, verified: true },
  { id: 'p-annamalaiyar-temple', slug: 'annamalaiyar-temple', name: 'Annamalaiyar Temple', display_name: 'Annamalaiyar Temple, Tiruvannamalai', type: 'TEMPLE', category: 'temple', subcategory: 'heritage', tagline: 'Pancha Bhoota Stalam representing Fire (Agni)', description: 'One of the largest temple complexes in India dedicated to Lord Shiva as Agni.', latitude: 12.2319, longitude: 79.0677, city: 'Tiruvannamalai', district: 'Tiruvannamalai', state: 'Tamil Nadu', country: 'India', region: 'Arunachala Sacred Region', aliases: ['arunachaleswarar temple'], activities: ['giri_pradakshina', 'temples'], tags: ['agni', 'shiva'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 4.9, verified: true },
  { id: 'p-gingee-fort', slug: 'gingee-fort', name: 'Gingee Fort', display_name: 'Gingee Fort, Villupuram', type: 'FORT', category: 'heritage', subcategory: 'fort', tagline: 'Impenetrable triple-citadel hill fort complex', description: 'Spanning three granite hills, renowned for Kalyana Mahal and 800-ft steep citadel climbs.', latitude: 12.2505, longitude: 79.4184, city: 'Gingee', district: 'Villupuram', state: 'Tamil Nadu', country: 'India', region: 'Gingee Hills', aliases: ['senji kottai'], activities: ['fort_climb', 'trekking'], tags: ['fort', 'citadel'], image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80', rating: 4.8, verified: true },
  { id: 'p-yercaud-hills', slug: 'yercaud-hills', name: 'Yercaud Hill Station', display_name: 'Yercaud Jewel of the South, Salem', type: 'HILL', category: 'mountain', subcategory: 'viewpoint', tagline: 'Jewel of the South at 1,515m MSL with 20 Hairpin Ghats', description: 'Tranquil hill station in the Shevaroy Hills of Eastern Ghats, famous for coffee plantations.', latitude: 11.7753, longitude: 78.2093, city: 'Yercaud', district: 'Salem', state: 'Tamil Nadu', country: 'India', region: 'Shevaroy Hills', aliases: ['yercaud'], activities: ['boating', 'viewpoints'], tags: ['hill_station', 'coffee'], image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80', rating: 4.7, verified: true },
  { id: 'p-kolli-hills', slug: 'kolli-hills', name: 'Kolli Hills 70 Hairpin Pass', display_name: 'Kolli Hills & 70 Hairpin Ghat Road, Namakkal', type: 'HILL', category: 'mountain', subcategory: 'offroad', tagline: 'Legendary 70 continuous hairpin bends ghat road to Agaya Gangai Falls', description: 'Mountain range in Eastern Ghats rising to 1,300m MSL, world-famous for its 70 hairpin bends.', latitude: 11.266, longitude: 78.337, city: 'Kolli Hills', district: 'Namakkal', state: 'Tamil Nadu', country: 'India', region: 'Eastern Ghats', aliases: ['kolli hills', 'agaya gangai'], activities: ['motorcycle_ride', 'hairpin_pass_drive'], tags: ['hairpin_bends', 'ghat_road'], image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80', rating: 4.8, verified: true },
  { id: 'p-hogenakkal-falls', slug: 'hogenakkal-falls', name: 'Hogenakkal Falls', display_name: 'Hogenakkal Falls & Coracle Rides, Dharmapuri', type: 'WATERFALL', category: 'waterfall', tagline: 'Niagara of India — Thundering Cauvery river canyon cascades', description: 'Series of cascading waterfalls on the Cauvery river, renowned for wicker coracle boat rides.', latitude: 12.1182, longitude: 77.7744, city: 'Hogenakkal', district: 'Dharmapuri', state: 'Tamil Nadu', country: 'India', region: 'Cauvery River Gorge', aliases: ['hogenakkal'], activities: ['coracle_ride', 'waterfalls'], tags: ['waterfall', 'coracle'], image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80', rating: 4.9, verified: true },
  { id: 'p-valparai-pass', slug: 'valparai-pass', name: 'Valparai 40 Hairpin Pass', display_name: 'Valparai Ghat Road & 40 Hairpin Bends', type: 'HILL', category: 'mountain', subcategory: 'offroad', tagline: '70km scenic tea plantation mountain pass with 40 sharp hairpin bends', description: 'High altitude tea town at 1,193m MSL in the Anamalai Hills.', latitude: 10.327, longitude: 76.9554, city: 'Valparai', district: 'Coimbatore', state: 'Tamil Nadu', country: 'India', region: 'Anamalai Hills', aliases: ['valparai'], activities: ['motorcycle_ride', 'tea_estate_walks'], tags: ['hairpin_bends', 'tea_plantation'], image: 'https://images.unsplash.com/photo-1589705298607-4e9640426b38?auto=format&fit=crop&w=1000&q=80', rating: 4.9, verified: true },
  { id: 'p-doddabetta-peak', slug: 'doddabetta-peak', name: 'Doddabetta Peak', display_name: 'Doddabetta Peak & Telescope House, Ooty', type: 'MOUNTAIN', category: 'mountain', subcategory: 'viewpoint', tagline: 'Highest mountain in the Nilgiri Hills at 2,637m MSL', description: 'The highest peak in the Nilgiri Mountains offering 360-degree panoramic views.', latitude: 11.4005, longitude: 76.7352, city: 'Ooty', district: 'The Nilgiris', state: 'Tamil Nadu', country: 'India', region: 'Nilgiri Plateau', aliases: ['doddabetta', 'ooty peak'], activities: ['viewpoints', 'nature_walks'], tags: ['highest_peak', 'viewpoint'], image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80', rating: 4.8, verified: true },
  { id: 'p-trichy-rockfort', slug: 'trichy-rockfort', name: 'Trichy Rockfort Temple', display_name: 'Trichy Rockfort Uchchi Pillayar Temple', type: 'FORT', category: 'heritage', subcategory: 'temple', tagline: '83-meter high ancient 3.8 billion-year-old rock-cut fortress temple', description: 'Historic fort and temple carved into a 273-foot high monolith in Tiruchirappalli.', latitude: 10.8288, longitude: 78.697, city: 'Tiruchirappalli', district: 'Tiruchirappalli', state: 'Tamil Nadu', country: 'India', region: 'Cauvery Delta', aliases: ['rockfort', 'trichy rockfort'], activities: ['rock_climb', 'temples'], tags: ['monolith', 'rock_cut'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 4.9, verified: true },
  { id: 'p-brihadisvara-temple', slug: 'brihadisvara-temple', name: 'Brihadisvara Temple (Big Temple)', display_name: 'Brihadisvara Temple Tanjore (Big Temple)', type: 'HERITAGE_SITE', category: 'heritage', subcategory: 'temple', tagline: '1010 AD Chola architectural climax — 216ft granite vimana', description: 'Built by Raja Raja Chola I in 1010 AD, a UNESCO World Heritage site constructed of granite.', latitude: 10.7828, longitude: 79.1318, city: 'Thanjavur', district: 'Thanjavur', state: 'Tamil Nadu', country: 'India', region: 'Cauvery Delta Capital', aliases: ['big temple thanjavur', 'brihadeeswarar temple'], activities: ['heritage', 'architecture'], tags: ['unesco', 'chola', 'big_temple'], image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80', rating: 5.0, verified: true },
  { id: 'p-meenakshi-temple', slug: 'meenakshi-temple', name: 'Meenakshi Amman Temple', display_name: 'Meenakshi Amman Temple, Madurai', type: 'TEMPLE', category: 'temple', subcategory: 'heritage', tagline: 'Historic Dravidian temple complex with 14 towering gopurams', description: 'The cultural center of Madurai, renowned for 33,000 sculptures, Hall of Thousand Pillars, and golden lotus tank.', latitude: 9.9195, longitude: 78.1193, city: 'Madurai', district: 'Madurai', state: 'Tamil Nadu', country: 'India', region: 'Madurai Heritage Zone', aliases: ['meenakshi temple', 'madurai meenakshi'], activities: ['temples', 'heritage', 'food'], tags: ['temple', 'gopuram', 'madurai'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 5.0, verified: true },
  { id: 'p-kodaikanal-lake', slug: 'kodaikanal-lake', name: 'Kodaikanal Lake & Coaker\'s Walk', display_name: 'Kodaikanal Lake & Coakers Walk, Dindigul', type: 'HILL', category: 'mountain', subcategory: 'lake', tagline: 'Star-shaped 60-acre artificial lake & panoramic mountain pedestrian walk', description: 'The centerpiece of Kodaikanal hill station, featuring pedal boating, cycling, and Coaker\'s Walk.', latitude: 10.2381, longitude: 77.4892, city: 'Kodaikanal', district: 'Dindigul', state: 'Tamil Nadu', country: 'India', region: 'Palani Hills', aliases: ['kodai lake', 'kodaikanal lake'], activities: ['boating', 'cycling', 'viewpoints'], tags: ['lake', 'hill_station'], image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80', rating: 4.8, verified: true },
  { id: 'p-suruli-falls', slug: 'suruli-falls', name: 'Suruli Waterfalls', display_name: 'Suruli Waterfalls & Meghamalai Foothills, Theni', type: 'WATERFALL', category: 'waterfall', tagline: '2-stage 150-ft cascades originating in Meghamalai Cloud Mountain', description: 'Famous 150-foot cascading falls in Theni district, surrounded by 18 rock-cut caves.', latitude: 9.6644, longitude: 77.2711, city: 'Cumbum / Surulipatti', district: 'Theni', state: 'Tamil Nadu', country: 'India', region: 'Western Ghats', aliases: ['suruli falls', 'suruli waterfalls'], activities: ['waterfalls', 'nature'], tags: ['waterfall', 'caves'], image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80', rating: 4.7, verified: true },
  { id: 'p-courtallam-falls', slug: 'courtallam-falls', name: 'Courtallam Main Falls', display_name: 'Courtallam Main Falls (Spa of South India), Tenkasi', type: 'WATERFALL', category: 'waterfall', tagline: 'Spa of South India — Herbal mineral medicinal waterfalls', description: 'Renowned medicinal waterfalls cascading over herbal forest rocks in the Western Ghats.', latitude: 8.9298, longitude: 77.2689, city: 'Courtallam', district: 'Tenkasi', state: 'Tamil Nadu', country: 'India', region: 'Western Ghats', aliases: ['courtallam', 'kourtallam'], activities: ['herbal_bath', 'waterfalls'], tags: ['waterfall', 'spa'], image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80', rating: 4.9, verified: true },
  { id: 'p-kanyakumari-sunset', slug: 'kanyakumari-sunset-point', name: 'Kanyakumari Triveni Sangam & Sunset Point', display_name: 'Triveni Sangam & Thiruvalluvar Statue, Kanyakumari', type: 'COASTAL', category: 'coastal', subcategory: 'monument', tagline: 'Southernmost tip of mainland India — Confluence of 3 seas', description: 'The geographic tip of India where Bay of Bengal, Arabian Sea, and Indian Ocean meet.', latitude: 8.0883, longitude: 77.5385, city: 'Kanyakumari', district: 'Kanyakumari', state: 'Tamil Nadu', country: 'India', region: 'Triveni Sangam', aliases: ['kanyakumari', 'triveni sangam'], activities: ['sunset_viewing', 'ferry_ride'], tags: ['confluence', 'monument', 'coastal'], image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1000&q=80', rating: 4.9, verified: true },
  { id: 'p-tiruchendur-temple', slug: 'tiruchendur-temple', name: 'Tiruchendur Murugan Temple', display_name: 'Tiruchendur Arulmigu Subramaniya Swamy Temple', type: 'TEMPLE', category: 'temple', subcategory: 'coastal', tagline: 'Second Arupadai Veedu Murugan seashore temple complex', description: 'Ancient seashore temple dedicated to Lord Murugan situated right on the Gulf of Mannar beach.', latitude: 8.4965, longitude: 78.1294, city: 'Tiruchendur', district: 'Thoothukudi', state: 'Tamil Nadu', country: 'India', region: 'Gulf of Mannar', aliases: ['tiruchendur', 'tiruchendur murugan temple'], activities: ['temples', 'sea_bath'], tags: ['arupadai_veedu', 'murugan', 'beach'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 4.9, verified: true },
  { id: 'p-palani-temple', slug: 'palani-temple', name: 'Palani Murugan Temple', display_name: 'Arulmigu Dhandayuthapani Swamy Temple, Palani', type: 'TEMPLE', category: 'temple', subcategory: 'mountain', tagline: 'Third Arupadai Veedu hill shrine reached by ropeway and winch', description: 'Sacred hill temple of Lord Murugan situated atop Sivagiri hill at 450m MSL.', latitude: 10.4477, longitude: 77.5204, city: 'Palani', district: 'Dindigul', state: 'Tamil Nadu', country: 'India', region: 'Palani Hills', aliases: ['palani', 'palani murugan temple'], activities: ['temples', 'ropeway_ride'], tags: ['arupadai_veedu', 'murugan', 'hill_temple'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 4.9, verified: true },
  { id: 'p-swamimalai-temple', slug: 'swamimalai-temple', name: 'Swamimalai Murugan Temple', display_name: 'Swamimalai Murugan Temple, Thanjavur', type: 'TEMPLE', category: 'temple', subcategory: 'heritage', tagline: 'Fourth Arupadai Veedu built atop a 60-step artificial hillock', description: 'Heritage temple where Lord Murugan imparted the Pranava Mantra to his father Lord Shiva.', latitude: 10.9566, longitude: 79.3275, city: 'Swamimalai', district: 'Thanjavur', state: 'Tamil Nadu', country: 'India', region: 'Cauvery Basin', aliases: ['swamimalai'], activities: ['temples', 'heritage'], tags: ['arupadai_veedu', 'murugan'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 4.8, verified: true },
  { id: 'p-tiruttani-temple', slug: 'tiruttani-temple', name: 'Tiruttani Murugan Temple', display_name: 'Tiruttani Murugan Temple, Tiruvallur', type: 'TEMPLE', category: 'temple', subcategory: 'mountain', tagline: 'Fifth Arupadai Veedu hill temple with 365 stone steps', description: 'Peaceful hill shrine of Lord Murugan situated on the hill of Thanikachalam.', latitude: 13.1788, longitude: 79.6074, city: 'Tiruttani', district: 'Tiruvallur', state: 'Tamil Nadu', country: 'India', region: 'Northern Tamil Nadu', aliases: ['tiruttani'], activities: ['temples', 'stair_climb'], tags: ['arupadai_veedu', 'murugan'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 4.8, verified: true },
  { id: 'p-palamuthircholai-temple', slug: 'palamuthircholai-temple', name: 'Pazhamudhircholai Murugan Temple', display_name: 'Pazhamudhircholai Murugan Temple, Solaimalai', type: 'TEMPLE', category: 'temple', subcategory: 'wildlife', tagline: 'Sixth Arupadai Veedu nestled in dense Solaimalai forest hills', description: 'Forest hill temple of Lord Murugan situated near Nupura Gangai holy spring in Solaimalai.', latitude: 10.0847, longitude: 78.2144, city: 'Solaimalai', district: 'Madurai', state: 'Tamil Nadu', country: 'India', region: 'Solaimalai Hills', aliases: ['palamuthircholai', 'pazhamudhircholai'], activities: ['temples', 'forest_walk'], tags: ['arupadai_veedu', 'murugan', 'forest'], image: 'https://images.unsplash.com/photo-1600100397608-f010e423b961?auto=format&fit=crop&w=1000&q=80', rating: 4.8, verified: true }
];

export default defineEventHandler((event) => {
  const query = getQuery(event);
  const category = (query.category as string)?.toLowerCase();
  const district = (query.district as string)?.toLowerCase();
  const q = (query.query as string || query.q as string)?.toLowerCase();

  let results = MASTER_SERVER_PLACES;

  if (category && category !== 'all') {
    results = results.filter((p) => p.category.toLowerCase() === category || p.subcategory?.toLowerCase() === category || p.tags?.includes(category));
  }

  if (district && district !== 'all' && district !== 'all districts') {
    results = results.filter((p) => p.district.toLowerCase() === district);
  }

  if (q) {
    results = results.filter((p) => 
      p.name.toLowerCase().includes(q) || 
      p.display_name.toLowerCase().includes(q) || 
      p.district.toLowerCase().includes(q) || 
      p.category.toLowerCase().includes(q)
    );
  }

  return {
    data: results,
    places: results,
    count: results.length,
    meta: { traceId: `tr-${Date.now()}`, timestamp: new Date().toISOString() }
  };
});
