/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as R500RouteImport } from './routes/500'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdventuresRouteImport } from './routes/adventures'
import { Route as AiPlanRouteImport } from './routes/ai-plan'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CoastalHeritageRouteImport } from './routes/coastal-heritage'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HillEscapesRouteImport } from './routes/hill-escapes'
import { Route as HillsOfTnRouteImport } from './routes/hills-of-tn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaduraiRouteImport } from './routes/madurai'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TheniRouteImport } from './routes/theni'
import { Route as TripPlannerRouteImport } from './routes/trip-planner'
import { Route as WesternGhatsRouteImport } from './routes/western-ghats'
import { Route as DistrictsIndexRouteImport } from './routes/districts.index'
import { Route as DistrictsDistrictSlugRouteImport } from './routes/districts.$districtSlug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as ExploreCategoryRouteImport } from './routes/explore.$category'
import { Route as LegalCommunityGuidelinesRouteImport } from './routes/legal.community-guidelines'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalSecurityRouteImport } from './routes/legal.security'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as PaymentPendingRouteImport } from './routes/payment.pending'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PlaceSlugRouteImport } from './routes/place.$slug'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as TrailsSlugRouteImport } from './routes/trails.$slug'
import { Route as TrailsArupadaiVeeduRouteImport } from './routes/trails.arupadai-veedu'
import { Route as TrailsPanchaBhootaRouteImport } from './routes/trails.pancha-bhoota'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresRoute = AdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPlanRoute = AiPlanRouteImport.update({
  id: '/ai-plan',
  path: '/ai-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CoastalHeritageRoute = CoastalHeritageRouteImport.update({
  id: '/coastal-heritage',
  path: '/coastal-heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HillEscapesRoute = HillEscapesRouteImport.update({
  id: '/hill-escapes',
  path: '/hill-escapes',
  getParentRoute: () => rootRouteImport,
} as any)
const HillsOfTnRoute = HillsOfTnRouteImport.update({
  id: '/hills-of-tn',
  path: '/hills-of-tn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaduraiRoute = MaduraiRouteImport.update({
  id: '/madurai',
  path: '/madurai',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TheniRoute = TheniRouteImport.update({
  id: '/theni',
  path: '/theni',
  getParentRoute: () => rootRouteImport,
} as any)
const TripPlannerRoute = TripPlannerRouteImport.update({
  id: '/trip-planner',
  path: '/trip-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const WesternGhatsRoute = WesternGhatsRouteImport.update({
  id: '/western-ghats',
  path: '/western-ghats',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsIndexRoute = DistrictsIndexRouteImport.update({
  id: '/districts/',
  path: '/districts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsDistrictSlugRoute = DistrictsDistrictSlugRouteImport.update({
  id: '/districts/$districtSlug',
  path: '/districts/$districtSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCategoryRoute = ExploreCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ExploreRoute,
} as any)
const LegalCommunityGuidelinesRoute =
  LegalCommunityGuidelinesRouteImport.update({
    id: '/legal/community-guidelines',
    path: '/legal/community-guidelines',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSecurityRoute = LegalSecurityRouteImport.update({
  id: '/legal/security',
  path: '/legal/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPendingRoute = PaymentPendingRouteImport.update({
  id: '/payment/pending',
  path: '/payment/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceSlugRoute = PlaceSlugRouteImport.update({
  id: '/place/$slug',
  path: '/place/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const TrailsSlugRoute = TrailsSlugRouteImport.update({
  id: '/trails/$slug',
  path: '/trails/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailsArupadaiVeeduRoute = TrailsArupadaiVeeduRouteImport.update({
  id: '/trails/arupadai-veedu',
  path: '/trails/arupadai-veedu',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailsPanchaBhootaRoute = TrailsPanchaBhootaRouteImport.update({
  id: '/trails/pancha-bhoota',
  path: '/trails/pancha-bhoota',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/admin': typeof AdminRoute
  '/adventures': typeof AdventuresRoute
  '/ai-plan': typeof AiPlanRoute
  '/billing': typeof BillingRoute
  '/coastal-heritage': typeof CoastalHeritageRoute
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/hill-escapes': typeof HillEscapesRoute
  '/hills-of-tn': typeof HillsOfTnRoute
  '/login': typeof LoginRoute
  '/madurai': typeof MaduraiRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/support': typeof SupportRoute
  '/theni': typeof TheniRoute
  '/trip-planner': typeof TripPlannerRoute
  '/western-ghats': typeof WesternGhatsRoute
  '/districts/$districtSlug': typeof DistrictsDistrictSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms': typeof LegalTermsRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/pending': typeof PaymentPendingRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/trails/$slug': typeof TrailsSlugRoute
  '/trails/arupadai-veedu': typeof TrailsArupadaiVeeduRoute
  '/trails/pancha-bhoota': typeof TrailsPanchaBhootaRoute
  '/districts/': typeof DistrictsIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/admin': typeof AdminRoute
  '/adventures': typeof AdventuresRoute
  '/ai-plan': typeof AiPlanRoute
  '/billing': typeof BillingRoute
  '/coastal-heritage': typeof CoastalHeritageRoute
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/hill-escapes': typeof HillEscapesRoute
  '/hills-of-tn': typeof HillsOfTnRoute
  '/login': typeof LoginRoute
  '/madurai': typeof MaduraiRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/support': typeof SupportRoute
  '/theni': typeof TheniRoute
  '/trip-planner': typeof TripPlannerRoute
  '/western-ghats': typeof WesternGhatsRoute
  '/districts/$districtSlug': typeof DistrictsDistrictSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms': typeof LegalTermsRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/pending': typeof PaymentPendingRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/trails/$slug': typeof TrailsSlugRoute
  '/trails/arupadai-veedu': typeof TrailsArupadaiVeeduRoute
  '/trails/pancha-bhoota': typeof TrailsPanchaBhootaRoute
  '/districts': typeof DistrictsIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/admin': typeof AdminRoute
  '/adventures': typeof AdventuresRoute
  '/ai-plan': typeof AiPlanRoute
  '/billing': typeof BillingRoute
  '/coastal-heritage': typeof CoastalHeritageRoute
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/hill-escapes': typeof HillEscapesRoute
  '/hills-of-tn': typeof HillsOfTnRoute
  '/login': typeof LoginRoute
  '/madurai': typeof MaduraiRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/support': typeof SupportRoute
  '/theni': typeof TheniRoute
  '/trip-planner': typeof TripPlannerRoute
  '/western-ghats': typeof WesternGhatsRoute
  '/districts/$districtSlug': typeof DistrictsDistrictSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/legal/community-guidelines': typeof LegalCommunityGuidelinesRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms': typeof LegalTermsRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/pending': typeof PaymentPendingRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/trails/$slug': typeof TrailsSlugRoute
  '/trails/arupadai-veedu': typeof TrailsArupadaiVeeduRoute
  '/trails/pancha-bhoota': typeof TrailsPanchaBhootaRoute
  '/districts/': typeof DistrictsIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/500'
    | '/admin'
    | '/adventures'
    | '/ai-plan'
    | '/billing'
    | '/coastal-heritage'
    | '/community'
    | '/discover'
    | '/explore'
    | '/hill-escapes'
    | '/hills-of-tn'
    | '/login'
    | '/madurai'
    | '/maintenance'
    | '/onboarding'
    | '/ops'
    | '/planner'
    | '/profile'
    | '/routes'
    | '/saved'
    | '/settings'
    | '/support'
    | '/theni'
    | '/trip-planner'
    | '/western-ghats'
    | '/districts/$districtSlug'
    | '/events/$slug'
    | '/explore/$category'
    | '/legal/community-guidelines'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/security'
    | '/legal/terms'
    | '/payment/failed'
    | '/payment/pending'
    | '/payment/success'
    | '/place/$slug'
    | '/settings/security'
    | '/trails/$slug'
    | '/trails/arupadai-veedu'
    | '/trails/pancha-bhoota'
    | '/districts/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/500'
    | '/admin'
    | '/adventures'
    | '/ai-plan'
    | '/billing'
    | '/coastal-heritage'
    | '/community'
    | '/discover'
    | '/explore'
    | '/hill-escapes'
    | '/hills-of-tn'
    | '/login'
    | '/madurai'
    | '/maintenance'
    | '/onboarding'
    | '/ops'
    | '/planner'
    | '/profile'
    | '/routes'
    | '/saved'
    | '/settings'
    | '/support'
    | '/theni'
    | '/trip-planner'
    | '/western-ghats'
    | '/districts/$districtSlug'
    | '/events/$slug'
    | '/explore/$category'
    | '/legal/community-guidelines'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/security'
    | '/legal/terms'
    | '/payment/failed'
    | '/payment/pending'
    | '/payment/success'
    | '/place/$slug'
    | '/settings/security'
    | '/trails/$slug'
    | '/trails/arupadai-veedu'
    | '/trails/pancha-bhoota'
    | '/districts'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/500'
    | '/admin'
    | '/adventures'
    | '/ai-plan'
    | '/billing'
    | '/coastal-heritage'
    | '/community'
    | '/discover'
    | '/explore'
    | '/hill-escapes'
    | '/hills-of-tn'
    | '/login'
    | '/madurai'
    | '/maintenance'
    | '/onboarding'
    | '/ops'
    | '/planner'
    | '/profile'
    | '/routes'
    | '/saved'
    | '/settings'
    | '/support'
    | '/theni'
    | '/trip-planner'
    | '/western-ghats'
    | '/districts/$districtSlug'
    | '/events/$slug'
    | '/explore/$category'
    | '/legal/community-guidelines'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/security'
    | '/legal/terms'
    | '/payment/failed'
    | '/payment/pending'
    | '/payment/success'
    | '/place/$slug'
    | '/settings/security'
    | '/trails/$slug'
    | '/trails/arupadai-veedu'
    | '/trails/pancha-bhoota'
    | '/districts/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R500Route: typeof R500Route
  AdminRoute: typeof AdminRoute
  AdventuresRoute: typeof AdventuresRoute
  AiPlanRoute: typeof AiPlanRoute
  BillingRoute: typeof BillingRoute
  CoastalHeritageRoute: typeof CoastalHeritageRoute
  CommunityRoute: typeof CommunityRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  HillEscapesRoute: typeof HillEscapesRoute
  HillsOfTnRoute: typeof HillsOfTnRoute
  LoginRoute: typeof LoginRoute
  MaduraiRoute: typeof MaduraiRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OnboardingRoute: typeof OnboardingRoute
  OpsRoute: typeof OpsRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  RoutesRoute: typeof RoutesRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SupportRoute: typeof SupportRoute
  TheniRoute: typeof TheniRoute
  TripPlannerRoute: typeof TripPlannerRoute
  WesternGhatsRoute: typeof WesternGhatsRoute
  DistrictsDistrictSlugRoute: typeof DistrictsDistrictSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  LegalCommunityGuidelinesRoute: typeof LegalCommunityGuidelinesRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalSecurityRoute: typeof LegalSecurityRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentPendingRoute: typeof PaymentPendingRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PlaceSlugRoute: typeof PlaceSlugRoute
  TrailsSlugRoute: typeof TrailsSlugRoute
  TrailsArupadaiVeeduRoute: typeof TrailsArupadaiVeeduRoute
  TrailsPanchaBhootaRoute: typeof TrailsPanchaBhootaRoute
  DistrictsIndexRoute: typeof DistrictsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures': {
      id: '/adventures'
      path: '/adventures'
      fullPath: '/adventures'
      preLoaderRoute: typeof AdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-plan': {
      id: '/ai-plan'
      path: '/ai-plan'
      fullPath: '/ai-plan'
      preLoaderRoute: typeof AiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coastal-heritage': {
      id: '/coastal-heritage'
      path: '/coastal-heritage'
      fullPath: '/coastal-heritage'
      preLoaderRoute: typeof CoastalHeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hill-escapes': {
      id: '/hill-escapes'
      path: '/hill-escapes'
      fullPath: '/hill-escapes'
      preLoaderRoute: typeof HillEscapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hills-of-tn': {
      id: '/hills-of-tn'
      path: '/hills-of-tn'
      fullPath: '/hills-of-tn'
      preLoaderRoute: typeof HillsOfTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/madurai': {
      id: '/madurai'
      path: '/madurai'
      fullPath: '/madurai'
      preLoaderRoute: typeof MaduraiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theni': {
      id: '/theni'
      path: '/theni'
      fullPath: '/theni'
      preLoaderRoute: typeof TheniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-planner': {
      id: '/trip-planner'
      path: '/trip-planner'
      fullPath: '/trip-planner'
      preLoaderRoute: typeof TripPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/western-ghats': {
      id: '/western-ghats'
      path: '/western-ghats'
      fullPath: '/western-ghats'
      preLoaderRoute: typeof WesternGhatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/': {
      id: '/districts/'
      path: '/districts'
      fullPath: '/districts/'
      preLoaderRoute: typeof DistrictsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts/$districtSlug': {
      id: '/districts/$districtSlug'
      path: '/districts/$districtSlug'
      fullPath: '/districts/$districtSlug'
      preLoaderRoute: typeof DistrictsDistrictSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$category': {
      id: '/explore/$category'
      path: '/$category'
      fullPath: '/explore/$category'
      preLoaderRoute: typeof ExploreCategoryRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/legal/community-guidelines': {
      id: '/legal/community-guidelines'
      path: '/legal/community-guidelines'
      fullPath: '/legal/community-guidelines'
      preLoaderRoute: typeof LegalCommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/security': {
      id: '/legal/security'
      path: '/legal/security'
      fullPath: '/legal/security'
      preLoaderRoute: typeof LegalSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/pending': {
      id: '/payment/pending'
      path: '/payment/pending'
      fullPath: '/payment/pending'
      preLoaderRoute: typeof PaymentPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$slug': {
      id: '/place/$slug'
      path: '/place/$slug'
      fullPath: '/place/$slug'
      preLoaderRoute: typeof PlaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/trails/$slug': {
      id: '/trails/$slug'
      path: '/trails/$slug'
      fullPath: '/trails/$slug'
      preLoaderRoute: typeof TrailsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trails/arupadai-veedu': {
      id: '/trails/arupadai-veedu'
      path: '/trails/arupadai-veedu'
      fullPath: '/trails/arupadai-veedu'
      preLoaderRoute: typeof TrailsArupadaiVeeduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trails/pancha-bhoota': {
      id: '/trails/pancha-bhoota'
      path: '/trails/pancha-bhoota'
      fullPath: '/trails/pancha-bhoota'
      preLoaderRoute: typeof TrailsPanchaBhootaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExploreRouteChildren {
  ExploreCategoryRoute: typeof ExploreCategoryRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreCategoryRoute: ExploreCategoryRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface SettingsRouteChildren {
  SettingsSecurityRoute: typeof SettingsSecurityRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSecurityRoute: SettingsSecurityRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R500Route: R500Route,
  AdminRoute: AdminRoute,
  AdventuresRoute: AdventuresRoute,
  AiPlanRoute: AiPlanRoute,
  BillingRoute: BillingRoute,
  CoastalHeritageRoute: CoastalHeritageRoute,
  CommunityRoute: CommunityRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRouteWithChildren,
  HillEscapesRoute: HillEscapesRoute,
  HillsOfTnRoute: HillsOfTnRoute,
  LoginRoute: LoginRoute,
  MaduraiRoute: MaduraiRoute,
  MaintenanceRoute: MaintenanceRoute,
  OnboardingRoute: OnboardingRoute,
  OpsRoute: OpsRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  RoutesRoute: RoutesRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SupportRoute: SupportRoute,
  TheniRoute: TheniRoute,
  TripPlannerRoute: TripPlannerRoute,
  WesternGhatsRoute: WesternGhatsRoute,
  DistrictsDistrictSlugRoute: DistrictsDistrictSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  LegalCommunityGuidelinesRoute: LegalCommunityGuidelinesRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalSecurityRoute: LegalSecurityRoute,
  LegalTermsRoute: LegalTermsRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentPendingRoute: PaymentPendingRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PlaceSlugRoute: PlaceSlugRoute,
  TrailsSlugRoute: TrailsSlugRoute,
  TrailsArupadaiVeeduRoute: TrailsArupadaiVeeduRoute,
  TrailsPanchaBhootaRoute: TrailsPanchaBhootaRoute,
  DistrictsIndexRoute: DistrictsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
