/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdventuresRouteImport } from './routes/adventures'
import { Route as CoastalHeritageRouteImport } from './routes/coastal-heritage'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HillEscapesRouteImport } from './routes/hill-escapes'
import { Route as HillsOfTnRouteImport } from './routes/hills-of-tn'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaduraiRouteImport } from './routes/madurai'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as TheniRouteImport } from './routes/theni'
import { Route as WesternGhatsRouteImport } from './routes/western-ghats'
import { Route as ExploreCategoryRouteImport } from './routes/explore.$category'
import { Route as PlaceSlugRouteImport } from './routes/place.$slug'
import { Route as TrailsArupadaiVeeduRouteImport } from './routes/trails.arupadai-veedu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresRoute = AdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const CoastalHeritageRoute = CoastalHeritageRouteImport.update({
  id: '/coastal-heritage',
  path: '/coastal-heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HillEscapesRoute = HillEscapesRouteImport.update({
  id: '/hill-escapes',
  path: '/hill-escapes',
  getParentRoute: () => rootRouteImport,
} as any)
const HillsOfTnRoute = HillsOfTnRouteImport.update({
  id: '/hills-of-tn',
  path: '/hills-of-tn',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaduraiRoute = MaduraiRouteImport.update({
  id: '/madurai',
  path: '/madurai',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const TheniRoute = TheniRouteImport.update({
  id: '/theni',
  path: '/theni',
  getParentRoute: () => rootRouteImport,
} as any)
const WesternGhatsRoute = WesternGhatsRouteImport.update({
  id: '/western-ghats',
  path: '/western-ghats',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCategoryRoute = ExploreCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ExploreRoute,
} as any)
const PlaceSlugRoute = PlaceSlugRouteImport.update({
  id: '/place/$slug',
  path: '/place/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailsArupadaiVeeduRoute = TrailsArupadaiVeeduRouteImport.update({
  id: '/trails/arupadai-veedu',
  path: '/trails/arupadai-veedu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adventures': typeof AdventuresRoute
  '/coastal-heritage': typeof CoastalHeritageRoute
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/hill-escapes': typeof HillEscapesRoute
  '/hills-of-tn': typeof HillsOfTnRoute
  '/login': typeof LoginRoute
  '/madurai': typeof MaduraiRoute
  '/ops': typeof OpsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/theni': typeof TheniRoute
  '/western-ghats': typeof WesternGhatsRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/trails/arupadai-veedu': typeof TrailsArupadaiVeeduRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adventures': typeof AdventuresRoute
  '/coastal-heritage': typeof CoastalHeritageRoute
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/hill-escapes': typeof HillEscapesRoute
  '/hills-of-tn': typeof HillsOfTnRoute
  '/login': typeof LoginRoute
  '/madurai': typeof MaduraiRoute
  '/ops': typeof OpsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/theni': typeof TheniRoute
  '/western-ghats': typeof WesternGhatsRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/trails/arupadai-veedu': typeof TrailsArupadaiVeeduRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adventures': typeof AdventuresRoute
  '/coastal-heritage': typeof CoastalHeritageRoute
  '/community': typeof CommunityRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/hill-escapes': typeof HillEscapesRoute
  '/hills-of-tn': typeof HillsOfTnRoute
  '/login': typeof LoginRoute
  '/madurai': typeof MaduraiRoute
  '/ops': typeof OpsRoute
  '/planner': typeof PlannerRoute
  '/profile': typeof ProfileRoute
  '/routes': typeof RoutesRoute
  '/theni': typeof TheniRoute
  '/western-ghats': typeof WesternGhatsRoute
  '/explore/$category': typeof ExploreCategoryRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/trails/arupadai-veedu': typeof TrailsArupadaiVeeduRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adventures'
    | '/coastal-heritage'
    | '/community'
    | '/discover'
    | '/explore'
    | '/hill-escapes'
    | '/hills-of-tn'
    | '/login'
    | '/madurai'
    | '/ops'
    | '/planner'
    | '/profile'
    | '/routes'
    | '/theni'
    | '/western-ghats'
    | '/explore/$category'
    | '/place/$slug'
    | '/trails/arupadai-veedu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/adventures'
    | '/coastal-heritage'
    | '/community'
    | '/discover'
    | '/explore'
    | '/hill-escapes'
    | '/hills-of-tn'
    | '/login'
    | '/madurai'
    | '/ops'
    | '/planner'
    | '/profile'
    | '/routes'
    | '/theni'
    | '/western-ghats'
    | '/explore/$category'
    | '/place/$slug'
    | '/trails/arupadai-veedu'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/adventures'
    | '/coastal-heritage'
    | '/community'
    | '/discover'
    | '/explore'
    | '/hill-escapes'
    | '/hills-of-tn'
    | '/login'
    | '/madurai'
    | '/ops'
    | '/planner'
    | '/profile'
    | '/routes'
    | '/theni'
    | '/western-ghats'
    | '/explore/$category'
    | '/place/$slug'
    | '/trails/arupadai-veedu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdventuresRoute: typeof AdventuresRoute
  CoastalHeritageRoute: typeof CoastalHeritageRoute
  CommunityRoute: typeof CommunityRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  HillEscapesRoute: typeof HillEscapesRoute
  HillsOfTnRoute: typeof HillsOfTnRoute
  LoginRoute: typeof LoginRoute
  MaduraiRoute: typeof MaduraiRoute
  OpsRoute: typeof OpsRoute
  PlannerRoute: typeof PlannerRoute
  ProfileRoute: typeof ProfileRoute
  RoutesRoute: typeof RoutesRoute
  TheniRoute: typeof TheniRoute
  WesternGhatsRoute: typeof WesternGhatsRoute
  PlaceSlugRoute: typeof PlaceSlugRoute
  TrailsArupadaiVeeduRoute: typeof TrailsArupadaiVeeduRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures': {
      id: '/adventures'
      path: '/adventures'
      fullPath: '/adventures'
      preLoaderRoute: typeof AdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coastal-heritage': {
      id: '/coastal-heritage'
      path: '/coastal-heritage'
      fullPath: '/coastal-heritage'
      preLoaderRoute: typeof CoastalHeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hill-escapes': {
      id: '/hill-escapes'
      path: '/hill-escapes'
      fullPath: '/hill-escapes'
      preLoaderRoute: typeof HillEscapesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hills-of-tn': {
      id: '/hills-of-tn'
      path: '/hills-of-tn'
      fullPath: '/hills-of-tn'
      preLoaderRoute: typeof HillsOfTnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/madurai': {
      id: '/madurai'
      path: '/madurai'
      fullPath: '/madurai'
      preLoaderRoute: typeof MaduraiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theni': {
      id: '/theni'
      path: '/theni'
      fullPath: '/theni'
      preLoaderRoute: typeof TheniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/western-ghats': {
      id: '/western-ghats'
      path: '/western-ghats'
      fullPath: '/western-ghats'
      preLoaderRoute: typeof WesternGhatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$category': {
      id: '/explore/$category'
      path: '/$category'
      fullPath: '/explore/$category'
      preLoaderRoute: typeof ExploreCategoryRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/place/$slug': {
      id: '/place/$slug'
      path: '/place/$slug'
      fullPath: '/place/$slug'
      preLoaderRoute: typeof PlaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trails/arupadai-veedu': {
      id: '/trails/arupadai-veedu'
      path: '/trails/arupadai-veedu'
      fullPath: '/trails/arupadai-veedu'
      preLoaderRoute: typeof TrailsArupadaiVeeduRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExploreRouteChildren {
  ExploreCategoryRoute: typeof ExploreCategoryRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreCategoryRoute: ExploreCategoryRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdventuresRoute: AdventuresRoute,
  CoastalHeritageRoute: CoastalHeritageRoute,
  CommunityRoute: CommunityRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRouteWithChildren,
  HillEscapesRoute: HillEscapesRoute,
  HillsOfTnRoute: HillsOfTnRoute,
  LoginRoute: LoginRoute,
  MaduraiRoute: MaduraiRoute,
  OpsRoute: OpsRoute,
  PlannerRoute: PlannerRoute,
  ProfileRoute: ProfileRoute,
  RoutesRoute: RoutesRoute,
  TheniRoute: TheniRoute,
  WesternGhatsRoute: WesternGhatsRoute,
  PlaceSlugRoute: PlaceSlugRoute,
  TrailsArupadaiVeeduRoute: TrailsArupadaiVeeduRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
